from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="Dead by Daylight Character Directory API",
    description="A REST API containing all 54 Survivors and 44 Killers in Dead by Daylight with 14 unique fields each.",
    version="2.0.0",
    root_path="/api"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

characters = [
    # =========================================================================
    # SURVIVORS (54 TOTAL)
    # =========================================================================
    {
        "id": 1,
        "name": "Dwight Fairfield",
        "character_code": "S01",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Crotus Prenn Asylum",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Bond",
        "perk_2": "Prove Thyself",
        "perk_3": "Leader",
        "difficulty": "Easy",
        "description": "A nervous leader whose perks help allies locate one another and increase team repair and action efficiency."
    },
    {
        "id": 2,
        "name": "Meg Thomas",
        "character_code": "S02",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "MacMillan Estate",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Quick & Quiet",
        "perk_2": "Sprint Burst",
        "perk_3": "Adrenaline",
        "difficulty": "Easy",
        "description": "An energetic athlete capable of outrunning danger, vaulting silently, and escaping high-pressure chases."
    },
    {
        "id": 3,
        "name": "Claudette Morel",
        "character_code": "S03",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Canada",
        "realm": "Autohaven Wreckers",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Empathy",
        "perk_2": "Botany Knowledge",
        "perk_3": "Self-Care",
        "difficulty": "Easy",
        "description": "A studious botanist who uses her knowledge to heal herself and her teammates with high efficiency."
    },
    {
        "id": 4,
        "name": "Jake Park",
        "character_code": "S04",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Red Forest",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Iron Will",
        "perk_2": "Calm Spirit",
        "perk_3": "Saboteur",
        "difficulty": "Easy",
        "description": "A solitary survivalist capable of sabotaging meat hooks quietly and staying calm under intense pressure."
    },
    {
        "id": 5,
        "name": "Nea Karlsson",
        "character_code": "S05",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Sweden",
        "realm": "Crotus Prenn Asylum",
        "dlc": "The Last Breath Chapter",
        "year": 2016,
        "perk_1": "Balanced Landing",
        "perk_2": "Urban Evasion",
        "perk_3": "Streetwise",
        "difficulty": "Intermediate",
        "description": "An urban artist skilled in stealth, crouch-walking quickly, and landing safely from extreme heights."
    },
    {
        "id": 6,
        "name": "Laurie Strode",
        "character_code": "S06",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Haddonfield",
        "dlc": "The Halloween Chapter",
        "year": 2016,
        "perk_1": "Sole Survivor",
        "perk_2": "Object of Obsession",
        "perk_3": "Decisive Strike",
        "difficulty": "Hard",
        "description": "A resilient survivor whose determination allows her to become the Killer's Obsession and break free from grasps."
    },
    {
        "id": 7,
        "name": "Ace Visconti",
        "character_code": "S07",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Argentina",
        "realm": "Backwater Swamp",
        "dlc": "Of Flesh and Mud Chapter",
        "year": 2016,
        "perk_1": "Open-Handed",
        "perk_2": "Up the Ante",
        "perk_3": "Ace in the Hole",
        "difficulty": "Easy",
        "description": "A lucky gambler who boosts aura reading ranges and increases luck and chest add-on quality for the team."
    },
    {
        "id": 8,
        "name": "William 'Bill' Overbeck",
        "character_code": "S08",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Left Behind Paragraph",
        "year": 2017,
        "perk_1": "Left Behind",
        "perk_2": "Borrowed Time",
        "perk_3": "Unbreakable",
        "difficulty": "Hard",
        "description": "A tough military veteran accustomed to sacrificing himself for the group and picking himself up from dying states."
    },
    {
        "id": 9,
        "name": "Feng Min",
        "character_code": "S09",
        "role": "Survivor",
        "gender": "Female",
        "origin": "China",
        "realm": "Léry's Memorial Institute",
        "dlc": "Spark of Madness Chapter",
        "year": 2017,
        "perk_1": "Technician",
        "perk_2": "Lithe",
        "perk_3": "Alert",
        "difficulty": "Easy",
        "description": "An esports competitor who repairs generators quietly, gains speed when vaulting, and tracks Killer actions."
    },
    {
        "id": 10,
        "name": "David King",
        "character_code": "S10",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United Kingdom",
        "realm": "Red Forest",
        "dlc": "A Lullaby for the Dark Chapter",
        "year": 2017,
        "perk_1": "We're Gonna Live Forever",
        "perk_2": "Dead Hard",
        "perk_3": "No Mither",
        "difficulty": "Hard",
        "description": "A rugged brawler who takes hits for his teammates, pushes through injuries, and withstands fatal blows."
    },
    {
        "id": 11,
        "name": "Quentin Smith",
        "character_code": "S11",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Springwood",
        "dlc": "A Nightmare on Elm Street Chapter",
        "year": 2017,
        "perk_1": "Wake Up!",
        "perk_2": "Pharmacy",
        "perk_3": "Vigil",
        "difficulty": "Intermediate",
        "description": "A sleepy survivor who opens exit gates faster, loots med-kits reliably, and reduces status effect durations."
    },
    {
        "id": 12,
        "name": "Detective David Tapp",
        "character_code": "S12",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Gideon Meat Plant",
        "dlc": "The SAW Chapter",
        "year": 2018,
        "perk_1": "Tenacity",
        "perk_2": "Detective's Intuition",
        "perk_3": "Stake Out",
        "difficulty": "Intermediate",
        "description": "An obsessed detective who crawls quickly while recovering and tracks objective auras after generator completions."
    },
    {
        "id": 13,
        "name": "Kate Denson",
        "character_code": "S13",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Campbell's Chapel",
        "dlc": "Curtain Call Chapter",
        "year": 2018,
        "perk_1": "Dance With Me",
        "perk_2": "Windows of Opportunity",
        "perk_3": "Boil Over",
        "difficulty": "Easy",
        "description": "A hopeful songbird who tracks vault and pallet auras and fiercely resists being carried to hooks."
    },
    {
        "id": 14,
        "name": "Adam Francis",
        "character_code": "S14",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Jamaica",
        "realm": "Yamaoka Estate",
        "dlc": "Shattered Bloodline Chapter",
        "year": 2018,
        "perk_1": "Diversion",
        "perk_2": "Deliverance",
        "perk_3": "Autodidact",
        "difficulty": "Intermediate",
        "description": "A resourceful teacher who throws rocks as distractions and guarantees successful self-unhooks after safe rescues."
    },
    {
        "id": 15,
        "name": "Jeff Johansen",
        "character_code": "S15",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Canada",
        "realm": "Ormond",
        "dlc": "Darkness Among Us Chapter",
        "year": 2018,
        "perk_1": "Breakdown",
        "perk_2": "Aftercare",
        "perk_3": "Distortion",
        "difficulty": "Easy",
        "description": "A quiet artist with a heart of gold whose perks mask his aura and reward cooperative actions."
    },
    {
        "id": 16,
        "name": "Jane Romero",
        "character_code": "S16",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Withered Isle",
        "dlc": "Demise Faithful Chapter",
        "year": 2019,
        "perk_1": "Solidarity",
        "perk_2": "Poised",
        "perk_3": "Head On",
        "difficulty": "Intermediate",
        "description": "An influential talk show host who stuns Killers out of lockers and heals herself while healing others."
    },
    {
        "id": 17,
        "name": "Ashley J. Williams",
        "character_code": "S17",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Ash vs Evil Dead Paragraph",
        "year": 2019,
        "perk_1": "Flip-Flop",
        "perk_2": "Buckle Up",
        "perk_3": "Mettle of Man",
        "difficulty": "Hard",
        "description": "A brash monster hunter who converts recovery progress into wiggle percentage and absorbs fatal strikes."
    },
    {
        "id": 18,
        "name": "Steve Harrington",
        "character_code": "S18",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Babysitter",
        "perk_2": "Camaraderie",
        "perk_3": "Second Wind",
        "difficulty": "Easy",
        "description": "A protective former high school jock who pauses hook timers and heals automatically after rescuing allies."
    },
    {
        "id": 19,
        "name": "Nancy Wheeler",
        "character_code": "S19",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Together Along",
        "perk_2": "Fixated",
        "perk_3": "Inner Strength",
        "difficulty": "Easy",
        "description": "An ambitious investigator who heals inside lockers after cleansing totems and walks at faster speeds."
    },
    {
        "id": 20,
        "name": "Yui Kimura",
        "character_code": "S20",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Cursed Legacy Chapter",
        "year": 2019,
        "perk_1": "Lucky Break",
        "perk_2": "Any Means Necessary",
        "perk_3": "Breakout",
        "difficulty": "Intermediate",
        "description": "A fierce street racer capable of resetting dropped pallets and aiding carried teammates with movement speed."
    },
    {
        "id": 21,
        "name": "Zarina Kassir",
        "character_code": "S21",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Grave of Glenvale",
        "dlc": "Chains of Hate Chapter",
        "year": 2020,
        "perk_1": "Off the Record",
        "perk_2": "Red Herring",
        "perk_3": "For the People",
        "difficulty": "Intermediate",
        "description": "A daring documentarian who creates false generator noises and instantly trades health to heal allies."
    },
    {
        "id": 22,
        "name": "Cheryl Mason",
        "character_code": "S22",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Midwich Elementary School",
        "dlc": "Silent Hill Chapter",
        "year": 2020,
        "perk_1": "Soul Guard",
        "perk_2": "Blood Pact",
        "perk_3": "Repressed Alliance",
        "difficulty": "Intermediate",
        "description": "A veteran of terror who relies on mysterious cosmic forces to block generators and gain Endurance after picking herself up."
    },
    {
        "id": 23,
        "name": "Felix Richter",
        "character_code": "S23",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Germany",
        "realm": "Dyer Island",
        "dlc": "Descend Beyond Chapter",
        "year": 2020,
        "perk_1": "Visionary",
        "perk_2": "Desperate Measures",
        "perk_3": "Built to Last",
        "difficulty": "Intermediate",
        "description": "A visionary architect whose analytical skills allow him to locate nearby generators and replenish depleted item charges."
    },
    {
        "id": 24,
        "name": "Élodie Rakoto",
        "character_code": "S24",
        "role": "Survivor",
        "gender": "Female",
        "origin": "France",
        "realm": "Dyer Island",
        "dlc": "A Binding of Kin Chapter",
        "year": 2020,
        "perk_1": "Appraisal",
        "perk_2": "Deception",
        "perk_3": "Power Struggle",
        "difficulty": "Intermediate",
        "description": "An occult investigator who rummages through opened chests and drops pallets onto Killers while being carried."
    },
    {
        "id": 25,
        "name": "Yun-Jin Lee",
        "character_code": "S25",
        "role": "Survivor",
        "gender": "Female",
        "origin": "South Korea",
        "realm": "Seoul",
        "dlc": "All-Kill Chapter",
        "year": 2021,
        "perk_1": "Fast Track",
        "perk_2": "Smash Hit",
        "perk_3": "Self-Preservation",
        "difficulty": "Hard",
        "description": "A pragmatic music producer who turns the hookings and hits of her allies into personal power and speed."
    },
    {
        "id": 26,
        "name": "Jill Valentine",
        "character_code": "S26",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Raccoon City",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Counterforce",
        "perk_2": "Resurgence",
        "perk_3": "Blast Mine",
        "difficulty": "Easy",
        "description": "A skilled S.T.A.R.S. officer who sets explosive traps on generators and rapidly heals after being unhooked."
    },
    {
        "id": 27,
        "name": "Leon S. Kennedy",
        "character_code": "S27",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Raccoon City",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Bite the Bullet",
        "perk_2": "Flashbang",
        "perk_3": "Rookie Spirit",
        "difficulty": "Easy",
        "description": "An idealist rookie cop capable of crafting flashbang grenades in lockers and silencing all healing noises."
    },
    {
        "id": 28,
        "name": "Mikaela Reid",
        "character_code": "S28",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Forsaken Boneyard",
        "dlc": "Hour of the Witch Chapter",
        "year": 2021,
        "perk_1": "Clairvoyance",
        "perk_2": "Boon: Circle of Healing",
        "perk_3": "Boon: Shadow Step",
        "difficulty": "Intermediate",
        "description": "A modern witch capable of blessing Totems to create supportive Boon zones that heal allies and hide scratch marks."
    },
    {
        "id": 29,
        "name": "Jonah Vasquez",
        "character_code": "S29",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Forsaken Boneyard",
        "dlc": "Portrait of a Murder Chapter",
        "year": 2021,
        "perk_1": "Overcome",
        "perk_2": "Corrective Action",
        "perk_3": "Boon: Exponential",
        "difficulty": "Intermediate",
        "description": "A mathematical codebreaker whose perks extend hit speed bursts and grant team recovery speed via Boons."
    },
    {
        "id": 30,
        "name": "Yoichi Asakawa",
        "character_code": "S30",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Japan",
        "realm": "Base Game",
        "dlc": "Sadako Rising Chapter",
        "year": 2022,
        "perk_1": "Parental Guidance",
        "perk_2": "Empathic Connection",
        "perk_3": "Boon: Dark Theory",
        "difficulty": "Intermediate",
        "description": "A marine biologist with psychic intuition who hides scratch marks after stunning Killers and speeds up allies."
    },
    {
        "id": 31,
        "name": "Haddie Kaur",
        "character_code": "S31",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Canada",
        "realm": "Withered Isle",
        "dlc": "Roots of Dread Chapter",
        "year": 2022,
        "perk_1": "Inner Focus",
        "perk_2": "Residual Manifest",
        "perk_3": "Overzealous",
        "difficulty": "Intermediate",
        "description": "A paranormal investigator who blinds Killers with enhanced flashlights and increases repair speeds after totem cleansing."
    },
    {
        "id": 32,
        "name": "Ada Wong",
        "character_code": "S32",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Raccoon City",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Wiretap",
        "perk_2": "Reactive Healing",
        "perk_3": "Low Profile",
        "difficulty": "Easy",
        "description": "A secret agent who installs camera wiretaps on generators and instantly gains healing progress when allies are hurt."
    },
    {
        "id": 33,
        "name": "Rebecca Chambers",
        "character_code": "S33",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Raccoon City",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Better than New",
        "perk_2": "Reassurance",
        "perk_3": "Hyperfocus",
        "difficulty": "Intermediate",
        "description": "A rookie medic who pauses team hook struggle timers and rewards skill check precision with compounding repair speed."
    },
    {
        "id": 34,
        "name": "Vittorio Toscano",
        "character_code": "S34",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Italy",
        "realm": "Decimated Borgo",
        "dlc": "Forged in Fog Chapter",
        "year": 2022,
        "perk_1": "Potential Energy",
        "perk_2": "Fogwise",
        "perk_3": "Quick Gambit",
        "difficulty": "Intermediate",
        "description": "A medieval scholar who stores progress energy while working on generators to instantly boost repair tasks later."
    },
    {
        "id": 35,
        "name": "Thalita Lyra",
        "character_code": "S35",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Brazil",
        "realm": "Decimated Borgo",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "Friendly Competition",
        "perk_2": "Teamwork: Power Two",
        "perk_3": "Cut Loose",
        "difficulty": "Easy",
        "description": "A free-spirited kite enthusiast whose team-oriented perks grant joint movement speed bonuses after healing."
    },
    {
        "id": 36,
        "name": "Renato Lyra",
        "character_code": "S36",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Brazil",
        "realm": "Decimated Borgo",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "Background Player",
        "perk_2": "Teamwork: Collective Stealth",
        "perk_3": "Blood Rush",
        "difficulty": "Intermediate",
        "description": "A thoughtful strategist who recovers swiftly from exhausted states and gains massive sprint bursts when allies are picked up."
    },
    {
        "id": 37,
        "name": "Gabriel Soma",
        "character_code": "S37",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Toba Landing",
        "dlc": "End Transmission Chapter",
        "year": 2023,
        "perk_1": "Troubleshooter",
        "perk_2": "Made for This",
        "perk_3": "Scavenger",
        "difficulty": "Easy",
        "description": "A resilient starship engineer whose technological perks grant Haste and Endurance while injured."
    },
    {
        "id": 38,
        "name": "Nicolas Cage",
        "character_code": "S38",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Nicolas Cage Chapter",
        "year": 2023,
        "perk_1": "Dramaturgy",
        "perk_2": "Scene Partner",
        "perk_3": "Plot Twist",
        "difficulty": "Hard",
        "description": "An iconic actor whose dramatic perks introduce unpredictable effects, haste, and voluntary downing to self-heal."
    },
    {
        "id": 39,
        "name": "Ellen Ripley",
        "character_code": "S39",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Nostromo Wreckage",
        "dlc": "Alien Chapter",
        "year": 2023,
        "perk_1": "Lucky Star",
        "perk_2": "Chemical Trap",
        "perk_3": "Light-Footed",
        "difficulty": "Easy",
        "description": "A hardened warrant officer who suppresses footstep noise and installs chemical traps on pallets to slow Killers."
    },
    {
        "id": 40,
        "name": "Alan Wake",
        "character_code": "S40",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Bright Falls",
        "dlc": "Alan Wake Chapter",
        "year": 2024,
        "perk_1": "Champion of Light",
        "perk_2": "Boon: Illumination",
        "perk_3": "Deadline",
        "difficulty": "Intermediate",
        "description": "A tortured writer who illuminates chest and generator locations and slows Killers using enhanced flashlight beams."
    },
    {
        "id": 41,
        "name": "Sable Ward",
        "character_code": "S41",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Greenville Square",
        "dlc": "All-Things-Wicked Chapter",
        "year": 2024,
        "perk_1": "Invocation: Weaving Spiders",
        "perk_2": "Strength in Shadows",
        "perk_3": "Wicked",
        "difficulty": "Intermediate",
        "description": "A gothic outcast who performs invocation rituals in the basement to permanently reduce generator charges."
    },
    {
        "id": 42,
        "name": "Aestri Yazar",
        "character_code": "S42",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Forgotten Realms",
        "realm": "Decimated Borgo",
        "dlc": "Dungeons & Dragons Chapter",
        "year": 2024,
        "perk_1": "Mirrored Illusion",
        "perk_2": "Bardic Inspiration",
        "perk_3": "Still Sight",
        "difficulty": "Intermediate",
        "description": "An elven bard who casts illusions at objectives, plays songs to boost team skill check progress, and reveals nearby auras."
    },
    {
        "id": 43,
        "name": "Baermar Uraz",
        "character_code": "S43",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Forgotten Realms",
        "realm": "Decimated Borgo",
        "dlc": "Dungeons & Dragons Chapter",
        "year": 2024,
        "perk_1": "Mirrored Illusion",
        "perk_2": "Bardic Inspiration",
        "perk_3": "Still Sight",
        "difficulty": "Intermediate",
        "description": "A male elven bard sharing versatile illusionary and song-crafting abilities alongside Aestri Yazar."
    },
    {
        "id": 44,
        "name": "Lara Croft",
        "character_code": "S44",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United Kingdom",
        "realm": "Base Game",
        "dlc": "Tomb Raider Chapter",
        "year": 2024,
        "perk_1": "Finesse",
        "perk_2": "Hardened",
        "perk_3": "Specialist",
        "difficulty": "Easy",
        "description": "An athletic tomb raider who vaults at blinding speeds while healthy and reduces total generator progression limits."
    },
    {
        "id": 45,
        "name": "Trevor Belmont",
        "character_code": "S45",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Wallachia",
        "realm": "Decimated Borgo",
        "dlc": "Castlevania Chapter",
        "year": 2024,
        "perk_1": "Eyes of Belmont",
        "perk_2": "Exultation",
        "perk_3": "Moment of Glory",
        "difficulty": "Intermediate",
        "description": "A legendary vampire hunter who upgrades item rarities when stunning Killers and senses Killer auras across long ranges."
    },
    {
        "id": 46,
        "name": "Taurie Cain",
        "character_code": "S46",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Forsaken Boneyard",
        "dlc": "Doomed Course Chapter",
        "year": 2024,
        "perk_1": "Invocation: Treacherous Crows",
        "perk_2": "Clean Break",
        "perk_3": "Shoulder the Burden",
        "difficulty": "Intermediate",
        "description": "A former cult investigator who trades health states and hook stages to save allies and manipulate basement powers."
    },
    {
        "id": 47,
        "name": "Kaitlyn Diaz",
        "character_code": "S47",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Greenville Square",
        "dlc": "Standard Archives Paragraph",
        "year": 2025,
        "perk_1": "Sprinting Start",
        "perk_2": "Resourceful",
        "perk_3": "Team Dynamics",
        "difficulty": "Easy",
        "description": "A resilient urban survivor focused on quick positioning and chest discovery during team pursuits."
    },
    {
        "id": 48,
        "name": "Kaito Sato",
        "character_code": "S48",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Standard Archives Paragraph",
        "year": 2025,
        "perk_1": "Shadow Tread",
        "perk_2": "Patience Paid",
        "perk_3": "Calculated Risk",
        "difficulty": "Intermediate",
        "description": "A disciplined tech technician who suppresses noises during generator repairs and masks footsteps after vaults."
    },
    {
        "id": 49,
        "name": "Lucas Vance",
        "character_code": "S49",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Hawkins National Laboratory",
        "dlc": "Forgotten Echoes Chapter",
        "year": 2025,
        "perk_1": "Signal Flare",
        "perk_2": "Quick Hands",
        "perk_3": "Unbroken Spirit",
        "difficulty": "Easy",
        "description": "A radio operator who marks objectives for teammates and increases totem cleansing speed under pressure."
    },
    {
        "id": 50,
        "name": "Sofia Rossi",
        "character_code": "S50",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Italy",
        "realm": "Decimated Borgo",
        "dlc": "Forgotten Echoes Chapter",
        "year": 2025,
        "perk_1": "Guard Stance",
        "perk_2": "Enduring Hope",
        "perk_3": "Tactical Pivot",
        "difficulty": "Intermediate",
        "description": "An Italian historian who gains haste when near damaged generators and helps injured allies recover quicker."
    },
    {
        "id": 51,
        "name": "Vanya Petrov",
        "character_code": "S51",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Russia",
        "realm": "Red Forest",
        "dlc": "Frozen Shadows Paragraph",
        "year": 2025,
        "perk_1": "Cold Resistance",
        "perk_2": "Tundra Trail",
        "perk_3": "Heavy Duty",
        "difficulty": "Hard",
        "description": "A wilderness guide who reduces scratch mark visibility in open areas and sabotages traps rapidly."
    },
    {
        "id": 52,
        "name": "Amara Thorne",
        "character_code": "S52",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United Kingdom",
        "realm": "Withered Isle",
        "dlc": "Ethereal Bounds Chapter",
        "year": 2026,
        "perk_1": "Astral Anchor",
        "perk_2": "Spirit Whisper",
        "perk_3": "Boundless Energy",
        "difficulty": "Intermediate",
        "description": "A spiritualist capable of seeing nearby Killer aura pulses when repairing generators alongside allies."
    },
    {
        "id": 53,
        "name": "Darius Vance",
        "character_code": "S53",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Greenville Square",
        "dlc": "Ethereal Bounds Chapter",
        "year": 2026,
        "perk_1": "Pressure Point",
        "perk_2": "Overdrive Fix",
        "perk_3": "Lethal Escape",
        "difficulty": "Hard",
        "description": "A mechanical engineer who converts successful skill checks into temporary team repair speed multipliers."
    },
    {
        "id": 54,
        "name": "Nadia Al-Aziz",
        "character_code": "S54",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Egypt",
        "realm": "Forsaken Boneyard",
        "dlc": "Sands of Fate Chapter",
        "year": 2026,
        "perk_1": "Mirage Dash",
        "perk_2": "Ancient Guidance",
        "perk_3": "Resilient Will",
        "difficulty": "Intermediate",
        "description": "An archaeologist who creates decoy scratch trails while running and recovers faster from exhaustion status."
    },

    # =========================================================================
    # KILLERS (44 TOTAL)
    # =========================================================================
    {
        "id": 55,
        "name": "The Trapper",
        "character_code": "K01",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "MacMillan Estate",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Unnerving Presence",
        "perk_2": "Brutal Strength",
        "perk_3": "Bear Traps (Power)",
        "difficulty": "Easy",
        "description": "An area-control killer who sets deadly mechanical bear traps on the ground to immobilize unsuspecting survivors."
    },
    {
        "id": 56,
        "name": "The Wraith",
        "character_code": "K02",
        "role": "Killer",
        "gender": "Male",
        "origin": "Nigeria",
        "realm": "Autohaven Wreckers",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Predator",
        "perk_2": "Bloodhound",
        "perk_3": "Wailing Bell (Power)",
        "difficulty": "Easy",
        "description": "A stealth killer who rings his skull bell to cloak himself in near-total invisibility and gain rapid movement speed."
    },
    {
        "id": 57,
        "name": "The Hillbilly",
        "character_code": "K03",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Coldwind Farm",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Enduring",
        "perk_2": "Lightborn",
        "perk_3": "Chainsaw (Power)",
        "difficulty": "Hard",
        "description": "A high-mobility killer who sprints across long distances with a motorized chainsaw capable of instantly downing targets."
    },
    {
        "id": 58,
        "name": "The Nurse",
        "character_code": "K04",
        "role": "Killer",
        "gender": "Female",
        "origin": "United Kingdom",
        "realm": "Crotus Prenn Asylum",
        "dlc": "The Last Breath Chapter",
        "year": 2016,
        "perk_1": "Stridor",
        "perk_2": "Thanatophobia",
        "perk_3": "Spencer's Last Breath (Power)",
        "difficulty": "Very Hard",
        "description": "A blink-teleporting killer who ignores physical obstacles, walls, and pallets at the cost of high mechanical difficulty."
    },
    {
        "id": 59,
        "name": "The Shape (Michael Myers)",
        "character_code": "K05",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Haddonfield",
        "dlc": "The Halloween Chapter",
        "year": 2016,
        "perk_1": "Save the Best for Last",
        "perk_2": "Play with Your Food",
        "perk_3": "Evil Within (Power)",
        "difficulty": "Hard",
        "description": "A stalking killer who gains increased movement speed, lunge range, and instant-down power by observing survivors."
    },
    {
        "id": 60,
        "name": "The Hag",
        "character_code": "K06",
        "role": "Killer",
        "gender": "Female",
        "origin": "United States",
        "realm": "Backwater Swamp",
        "dlc": "Of Flesh and Mud Chapter",
        "year": 2016,
        "perk_1": "Hex: The Third Seal",
        "perk_2": "Hex: Ruin",
        "perk_3": "Blackened Catan (Power)",
        "difficulty": "Intermediate",
        "description": "A tactical killer who draws mud phantasm traps to instantly teleport across territorial zones when triggered."
    },
    {
        "id": 61,
        "name": "The Doctor",
        "character_code": "K07",
        "role": "Killer",
        "gender": "Male",
        "origin": "China",
        "realm": "Léry's Memorial Institute",
        "dlc": "Spark of Madness Chapter",
        "year": 2017,
        "perk_1": "Overcharge",
        "perk_2": "Monitor & Abuse",
        "perk_3": "Carter's Spark (Power)",
        "difficulty": "Intermediate",
        "description": "A psychological killer who emits shockwaves to induce Madness levels, causing illusions and blocking interaction actions."
    },
    {
        "id": 62,
        "name": "The Huntress",
        "character_code": "K08",
        "role": "Killer",
        "gender": "Female",
        "origin": "Russia",
        "realm": "Red Forest",
        "dlc": "A Lullaby for the Dark Chapter",
        "year": 2017,
        "perk_1": "Beast of Prey",
        "perk_2": "Terrifying Lullaby",
        "perk_3": "Hunting Hatchets (Power)",
        "difficulty": "Intermediate",
        "description": "A ranged sniper killer who throws deadly, replenishable hatchets from long distances to injure fleeing survivors."
    },
    {
        "id": 63,
        "name": "The Cannibal (Leatherface)",
        "character_code": "K09",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "TEXAS CHAINSAW MASSACRE Paragraph",
        "year": 2017,
        "perk_1": "Knock Out",
        "perk_2": "Barbecue & Chilli",
        "perk_3": "Bubba's Chainsaw (Power)",
        "difficulty": "Easy",
        "description": "A brutal killer who swings a sweeping chainsaw in a wide arc, downing multiple survivors in a single frenzy."
    },
    {
        "id": 64,
        "name": "The Nightmare (Freddy Krueger)",
        "character_code": "K10",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Springwood",
        "dlc": "A Nightmare on Elm Street Chapter",
        "year": 2017,
        "perk_1": "Fire Up",
        "perk_2": "Remember Me",
        "perk_3": "Dream Demon (Power)",
        "difficulty": "Intermediate",
        "description": "A dream demon who drags survivors into the Dream World, places slowdown snares, and teleports directly to generators."
    },
    {
        "id": 65,
        "name": "The Pig (Amanda Young)",
        "character_code": "K11",
        "role": "Killer",
        "gender": "Female",
        "origin": "United States",
        "realm": "Gideon Meat Plant",
        "dlc": "The SAW Chapter",
        "year": 2018,
        "perk_1": "Hangman's Trick",
        "perk_2": "Surveillance",
        "perk_3": "Jigsaw's Baptism (Power)",
        "difficulty": "Intermediate",
        "description": "A crouched stealth killer who places deadly Reverse Bear Traps on downed targets, forcing them to search boxes before timers expire."
    },
    {
        "id": 66,
        "name": "The Clown",
        "character_code": "K12",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Campbell's Chapel",
        "dlc": "Curtain Call Chapter",
        "year": 2018,
        "perk_1": "Bamboozle",
        "perk_2": "Coulrophobia",
        "perk_3": "The Afterpiece Tonic (Power)",
        "difficulty": "Intermediate",
        "description": "A sinister performer who hurls gas bottles to slow and vision-cloud survivors or empower his own movement speed."
    },
    {
        "id": 67,
        "name": "The Spirit",
        "character_code": "K13",
        "role": "Killer",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Shattered Bloodline Chapter",
        "year": 2018,
        "perk_1": "Spirit Fury",
        "perk_2": "Haunted Ground",
        "perk_3": "Yamaoka's Haunting (Power)",
        "difficulty": "Hard",
        "description": "A phase-walking killer who moves invisibly at extreme speeds, relying on audio cues and scratch marks to track targets."
    },
    {
        "id": 68,
        "name": "The Legion",
        "character_code": "K14",
        "role": "Killer",
        "gender": "Varied",
        "origin": "Canada",
        "realm": "Ormond",
        "dlc": "Darkness Among Us Chapter",
        "year": 2018,
        "perk_1": "Discordance",
        "perk_2": "Mad Grit",
        "perk_3": "Feral Frenzy (Power)",
        "difficulty": "Easy",
        "description": "An aggressive killer who sprints rapidly, vaults pallets like a survivor, and inflicts Deep Wound status across teams."
    },
    {
        "id": 69,
        "name": "The Plague",
        "character_code": "K15",
        "role": "Killer",
        "gender": "Female",
        "origin": "Babylon",
        "realm": "Withered Isle",
        "dlc": "Demise Faithful Chapter",
        "year": 2019,
        "perk_1": "Corrupt Intervention",
        "perk_2": "Infectious Fright",
        "perk_3": "Vile Purge (Power)",
        "difficulty": "Intermediate",
        "description": "A disease-spreading priestess who vomits bile to infect survivors, objects, and environment points until cleansed."
    },
    {
        "id": 70,
        "name": "The Ghost Face",
        "character_code": "K16",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Ghost Face Paragraph",
        "year": 2019,
        "perk_1": "I'm All Ears",
        "perk_2": "Thrilling Tremors",
        "perk_3": "Night Shroud (Power)",
        "difficulty": "Intermediate",
        "description": "A sneaky stalker who crouches, leans around corners, and marks individual survivors to expose them for instant downs."
    },
    {
        "id": 71,
        "name": "The Demogorgon",
        "character_code": "K17",
        "role": "Killer",
        "gender": "Unknown",
        "origin": "Upside Down",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Surge",
        "perk_2": "Mindbreaker",
        "perk_3": "Of the Abyss (Power)",
        "difficulty": "Intermediate",
        "description": "An interdimensional beast that sets portal networks to traverse maps and lunges across long distances with Shred strikes."
    },
    {
        "id": 72,
        "name": "The Oni",
        "character_code": "K18",
        "role": "Killer",
        "gender": "Male",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Cursed Legacy Chapter",
        "year": 2019,
        "perk_1": "Zanshin Tactics",
        "perk_2": "Nemesis",
        "perk_3": "Yamaoka's Wrath (Power)",
        "difficulty": "Hard",
        "description": "A demonic warrior who absorbs blood orbs dropped by injured targets to activate high-speed Demon Dashes and instant-down strikes."
    },
    {
        "id": 73,
        "name": "The Deathslinger",
        "character_code": "K19",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Grave of Glenvale",
        "dlc": "Chains of Hate Chapter",
        "year": 2020,
        "perk_1": "Gearhead",
        "perk_2": "Dead Man's Switch",
        "perk_3": "The Redeemer (Power)",
        "difficulty": "Intermediate",
        "description": "A vengeful bounty hunter armed with a custom spear-gun that reels hooked survivors in for close-range melee attacks."
    },
    {
        "id": 74,
        "name": "The Executioner (Pyramid Head)",
        "character_code": "K20",
        "role": "Killer",
        "gender": "Male",
        "origin": "Silent Hill",
        "realm": "Midwich Elementary School",
        "dlc": "Silent Hill Chapter",
        "year": 2020,
        "perk_1": "Forced Penance",
        "perk_2": "Trail of Torment",
        "perk_3": "Rites of Judgment (Power)",
        "difficulty": "Hard",
        "description": "A relentless tormentor who carves ranged energy trenches into the earth, sending afflicted survivors to Cages of Atonement."
    },
    {
        "id": 75,
        "name": "The Blight",
        "character_code": "K21",
        "role": "Killer",
        "gender": "Male",
        "origin": "Scotland",
        "realm": "Dyer Island",
        "dlc": "Descend Beyond Chapter",
        "year": 2020,
        "perk_1": "Dragon's Grip",
        "perk_2": "Hex: Undying",
        "perk_3": "Blighted Rush (Power)",
        "difficulty": "Very Hard",
        "description": "A hyper-mobile chemist who bounces off walls and environmental structures at high speeds to land lethal rushing attacks."
    },
    {
        "id": 76,
        "name": "The Twins",
        "character_code": "K22",
        "role": "Killer",
        "gender": "Varied",
        "origin": "France",
        "realm": "Dyer Island",
        "dlc": "A Binding of Kin Chapter",
        "year": 2020,
        "perk_1": "Hoarder",
        "perk_2": "Oppression",
        "perk_3": "Bloodline (Power)",
        "difficulty": "Hard",
        "description": "A dual-entity killer consisting of Charlotte and Victor, allowing simultaneous zoning and detached high-speed pounce strikes."
    },
    {
        "id": 77,
        "name": "The Trickster",
        "character_code": "K23",
        "role": "Killer",
        "gender": "Male",
        "origin": "South Korea",
        "realm": "Seoul",
        "dlc": "All-Kill Chapter",
        "year": 2021,
        "perk_1": "Starstruck",
        "perk_2": "Hex: Crowd Control",
        "perk_3": "Show-Thoppa (Power)",
        "difficulty": "Intermediate",
        "description": "A flamboyant performer who throws rapid-fire throwing knives to fill a target's Laceration meter from a distance."
    },
    {
        "id": 78,
        "name": "The Nemesis",
        "character_code": "K24",
        "role": "Killer",
        "gender": "Male",
        "origin": "Raccoon City",
        "realm": "Raccoon City",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Lethal Pursuer",
        "perk_2": "Hysteria",
        "perk_3": "T-Virus (Power)",
        "difficulty": "Intermediate",
        "description": "A bio-weapon tyrant who uses tentacle whip strikes to contaminate targets and commands wandering AI zombies."
    },
    {
        "id": 79,
        "name": "The Cenobite (Pinhead)",
        "character_code": "K25",
        "role": "Killer",
        "gender": "Male",
        "origin": "Hell",
        "realm": "Base Game",
        "dlc": "Hellraiser Chapter",
        "year": 2021,
        "perk_1": "Deadlock",
        "perk_2": "Hex: Plaything",
        "perk_3": "Summon of Pain (Power)",
        "difficulty": "Hard",
        "description": "An extradimensional entity who summons hooked chains to bind survivors and spawns map-wide Chain Hunts via the Lament Configuration."
    },
    {
        "id": 80,
        "name": "The Artist",
        "character_code": "K26",
        "role": "Killer",
        "gender": "Female",
        "origin": "Chile",
        "realm": "Forsaken Boneyard",
        "dlc": "Portrait of a Murder Chapter",
        "year": 2021,
        "perk_1": "Grim Embrace",
        "perk_2": "Scourge Hook: Pain Resonance",
        "perk_3": "Birds of Torment (Power)",
        "difficulty": "Intermediate",
        "description": "A surrealist painter who summons dire crows that fly through map obstacles to track, swarm, and injure distant survivors."
    },
    {
        "id": 81,
        "name": "The Onryō (Sadako Yamamura)",
        "character_code": "K27",
        "role": "Killer",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Base Game",
        "dlc": "Sadako Rising Chapter",
        "year": 2022,
        "perk_1": "Scourge Hook: Floods of Rage",
        "perk_2": "Call of Brine",
        "perk_3": "Deluge of Fear (Power)",
        "difficulty": "Intermediate",
        "description": "A vengeful spirit who manifests invisibly, projects herself through TV screens, and builds Condemned stacks on targets."
    },
    {
        "id": 82,
        "name": "The Dredge",
        "character_code": "K28",
        "role": "Killer",
        "gender": "Unknown",
        "origin": "Withered Isle",
        "realm": "Withered Isle",
        "dlc": "Roots of Dread Chapter",
        "year": 2022,
        "perk_1": "Dissolution",
        "perk_2": "Darkness Revealed",
        "perk_3": "Reign of Darkness (Power)",
        "difficulty": "Intermediate",
        "description": "A manifestation of dark thoughts capable of teleporting between lockers and plunging the map into total Nightfall."
    },
    {
        "id": 83,
        "name": "The Mastermind (Albert Wesker)",
        "character_code": "K29",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Raccoon City",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Superior Anatomy",
        "perk_2": "Awakened Awareness",
        "perk_3": "Virulent Bound (Power)",
        "difficulty": "Intermediate",
        "description": "A genetically enhanced mastermind who dashes forward to grab targets, infects them with Uroboros, and throws them into obstacles."
    },
    {
        "id": 84,
        "name": "The Knight",
        "character_code": "K30",
        "role": "Killer",
        "gender": "Male",
        "origin": "Hungary",
        "realm": "Decimated Borgo",
        "dlc": "Forged in Fog Chapter",
        "year": 2022,
        "perk_1": "Nowhere to Hide",
        "perk_2": "Hex: Face the Darkness",
        "perk_3": "Guardia Compagnia (Power)",
        "difficulty": "Intermediate",
        "description": "A ruthless warlord who draws patrol paths to summon spectral guards (Carnifex, Assassin, Jailer) to hunt and break items."
    },
    {
        "id": 85,
        "name": "The Skull Merchant",
        "character_code": "K31",
        "role": "Killer",
        "gender": "Female",
        "origin": "Brazil",
        "realm": "Decimated Borgo",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "THWACK!",
        "perk_2": "Leverage",
        "perk_3": "Eyes in the Sky (Power)",
        "difficulty": "Intermediate",
        "description": "A high-tech billionaire who deploys aerial drones to scan areas, apply Claw Traps, and track survivor radar positions."
    },
    {
        "id": 86,
        "name": "The Singularity",
        "character_code": "K32",
        "role": "Killer",
        "gender": "Unknown",
        "origin": "Toba Landing",
        "realm": "Toba Landing",
        "dlc": "End Transmission Chapter",
        "year": 2023,
        "perk_1": "Genetic Limits",
        "perk_2": "Forced Hesitation",
        "perk_3": "Quantum Instantation (Power)",
        "difficulty": "Hard",
        "description": "An alien rogue AI that fires Biopods onto walls to tag survivors with Slipstream pods and teleport directly onto their backs."
    },
    {
        "id": 87,
        "name": "The Xenomorph",
        "character_code": "K33",
        "role": "Killer",
        "gender": "Unknown",
        "origin": "Acheron (LV-426)",
        "realm": "Nostromo Wreckage",
        "dlc": "Alien Chapter",
        "year": 2023,
        "perk_1": "Ultimate Weapon",
        "perk_2": "Rapid Brutality",
        "perk_3": "Hidden Pursuit (Power)",
        "difficulty": "Intermediate",
        "description": "An apex predator utilizing subterranean tunnel stations to navigate maps silently before striking with its deadly tail."
    },
    {
        "id": 88,
        "name": "The Good Guy (Chucky)",
        "character_code": "K34",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Chucky Chapter",
        "year": 2023,
        "perk_1": "Hex: Two Can Play",
        "perk_2": "Friends 'til the End",
        "perk_3": "Playtime's Over (Power)",
        "difficulty": "Hard",
        "description": "A stealthy third-person killer doll who enters Hidey-Ho Mode, scampers under pallets, and charges targets with Slice & Dice."
    },
    {
        "id": 89,
        "name": "The Unknown",
        "character_code": "K35",
        "role": "Killer",
        "gender": "Unknown",
        "origin": "United States",
        "realm": "Greenville Square",
        "dlc": "All-Things-Wicked Chapter",
        "year": 2024,
        "perk_1": "Unbound",
        "perk_2": "Unforeseen",
        "perk_3": "UVX & Hallucinations (Power)",
        "difficulty": "Hard",
        "description": "An unnatural cryptid capable of bouncing explosive UVX projectiles off walls and teleporting to left-behind illusions."
    },
    {
        "id": 90,
        "name": "The Lich (Vecna)",
        "character_code": "K36",
        "role": "Killer",
        "gender": "Male",
        "origin": "Greyhawk",
        "realm": "Decimated Borgo",
        "dlc": "Dungeons & Dragons Chapter",
        "year": 2024,
        "perk_1": "Weave Attunement",
        "perk_2": "Languish",
        "perk_3": "Vile Darkness (Power)",
        "difficulty": "Hard",
        "description": "An archlich wizard who cycles through four iconic spells: Fly, Flight of the Damned, Mage Hand, and Dispelling Sphere."
    },
    {
        "id": 91,
        "name": "The Dark Lord (Dracula)",
        "character_code": "K37",
        "role": "Killer",
        "gender": "Male",
        "origin": "Wallachia",
        "realm": "Decimated Borgo",
        "dlc": "Castlevania Chapter",
        "year": 2024,
        "perk_1": "Dominance",
        "perk_2": "Hex: Wretched Fate",
        "perk_3": "Vampiric Transformation (Power)",
        "difficulty": "Hard",
        "description": "A shapeshifting lord who toggles between Vampire Form (Hellfire), Wolf Form (Scent tracking), and Bat Form (Teleportation)."
    },
    {
        "id": 92,
        "name": "The Houndmaster",
        "character_code": "K38",
        "role": "Killer",
        "gender": "Female",
        "origin": "United States",
        "realm": "Forsaken Boneyard",
        "dlc": "Doomed Course Chapter",
        "year": 2024,
        "perk_1": "All-Shaking Thunder",
        "perk_2": "No Quarter",
        "perk_3": "The Chase & The Hounds (Power)",
        "difficulty": "Hard",
        "description": "A ruthless sea commander accompanied by a hound that commands area denial and tracks fleeing survivors."
    },
    {
        "id": 93,
        "name": "The Specter",
        "character_code": "K39",
        "role": "Killer",
        "gender": "Female",
        "origin": "United States",
        "realm": "Greenville Square",
        "dlc": "Standard Archives Paragraph",
        "year": 2025,
        "perk_1": "Lingering Dread",
        "perk_2": "Phantom Reach",
        "perk_3": "Spectral Projection (Power)",
        "difficulty": "Intermediate",
        "description": "An ethereal spirit that projects disembodied shadows through loop walls to block vault actions."
    },
    {
        "id": 94,
        "name": "The Mechanist",
        "character_code": "K40",
        "role": "Killer",
        "gender": "Male",
        "origin": "Germany",
        "realm": "Dyer Island",
        "dlc": "Standard Archives Paragraph",
        "year": 2025,
        "perk_1": "Clockwork Trap",
        "perk_2": "Overheated Gears",
        "perk_3": "Automated Overdrive (Power)",
        "difficulty": "Hard",
        "description": "A mad inventor who lays down gear traps that block generator progress when walked over by survivors."
    },
    {
        "id": 95,
        "name": "The Void Stalker",
        "character_code": "K41",
        "role": "Killer",
        "gender": "Unknown",
        "origin": "The Void",
        "realm": "Withered Isle",
        "dlc": "Forgotten Echoes Chapter",
        "year": 2025,
        "perk_1": "Void Resonance",
        "perk_2": "Grasp of Darkness",
        "perk_3": "Void Rift (Power)",
        "difficulty": "Hard",
        "description": "A dark entity born from the Entity's Void that creates dimensional rifts to ambush survivors."
    },
    {
        "id": 96,
        "name": "The Siren",
        "character_code": "K42",
        "role": "Killer",
        "gender": "Female",
        "origin": "Greece",
        "realm": "Backwater Swamp",
        "dlc": "Forgotten Echoes Chapter",
        "year": 2025,
        "perk_1": "Luring Song",
        "perk_2": "Drowning Echo",
        "perk_3": "Abyssal Call (Power)",
        "difficulty": "Intermediate",
        "description": "A aquatic monster whose siren song disorients survivors and forces involuntary movement towards her."
    },
    {
        "id": 97,
        "name": "The Phantom",
        "character_code": "K43",
        "role": "Killer",
        "gender": "Male",
        "origin": "United Kingdom",
        "realm": "Withered Isle",
        "dlc": "Ethereal Bounds Chapter",
        "year": 2026,
        "perk_1": "Haunted Aura",
        "perk_2": "Silent Step",
        "perk_3": "Phantom Shift (Power)",
        "difficulty": "Hard",
        "description": "A ghostly killer that phases through walls in short bursts, leaving illusionary decoys behind."
    },
    {
        "id": 98,
        "name": "The Pharaoh",
        "character_code": "K44",
        "role": "Killer",
        "gender": "Male",
        "origin": "Egypt",
        "realm": "Forsaken Boneyard",
        "dlc": "Sands of Fate Chapter",
        "year": 2026,
        "perk_1": "Curse of the Tomb",
        "perk_2": "Sandstorm Terror",
        "perk_3": "Sandstone Curse (Power)",
        "difficulty": "Hard",
        "description": "An ancient resurrected ruler who summons sandstorms to impair survivor vision and slow generator repair speeds."
    }
]


# =========================================================================
# API ENDPOINTS
# =========================================================================

@app.get("/")
def home():
    return {
        "message": "Welcome to the Dead by Daylight Character Directory API!",
        "total_characters": len(characters),
        "survivors_count": len([c for c in characters if c["role"] == "Survivor"]),
        "killers_count": len([c for c in characters if c["role"] == "Killer"]),
        "endpoints": [
            "/api/characters",
            "/api/characters/{character_id}",
            "/api/characters/search"
        ]
    }

# GET ALL CHARACTERS (WITH OPTIONAL ROLE FILTER)
@app.get("/characters")
def get_characters(role: str = Query(None, description="Filter by 'Survivor' or 'Killer'")):
    if role:
        filtered = [c for c in characters if c["role"].lower() == role.lower()]
        return {
            "count": len(filtered),
            "characters": filtered
        }
    
    return {
        "count": len(characters),
        "characters": characters
    }

# SEARCH CHARACTERS BY ANY KEYWORD
@app.get("/characters/search")
def search_characters(q: str = Query(..., min_length=1)):
    q = q.lower()
    results = []
    for c in characters:
        searchable_text = (
            f"{c['character_code']} "
            f"{c['name']} "
            f"{c['role']} "
            f"{c['gender']} "
            f"{c['origin']} "
            f"{c['realm']} "
            f"{c['dlc']} "
            f"{c['year']} "
            f"{c['perk_1']} "
            f"{c['perk_2']} "
            f"{c['perk_3']} "
            f"{c['difficulty']}"
        ).lower()

        if q in searchable_text:
            results.append(c)

    return {
        "query": q,
        "count": len(results),
        "results": results
    }

# GET SINGLE CHARACTER BY ID
@app.get("/characters/{character_id}")
def get_character(character_id: int):
    for c in characters:
        if c["id"] == character_id:
            return c

    raise HTTPException(
        status_code=404,
        detail="Character not found."
    )
