from fastapi import FastAPI, HTTPException, Header, Query, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import datetime, timezone

# ============================================================
# CONFIGURATION & CONSTANTS
# ============================================================
API_KEY = "student-api-key-123"
API_VERSION = "1.0"

app = FastAPI(
    title="Dead by Daylight Character Directory API",
    description="A REST API containing all Survivors and Killers in Dead by Daylight",
    version=API_VERSION
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# MODEL
# ============================================================
class Character(BaseModel):
    id: int
    name: str = Field(min_length=1)
    character_code: str = Field(min_length=1)
    role: Literal["Survivor", "Killer"]
    gender: str = Field(min_length=1)
    origin: str = Field(min_length=1)
    realm: str = Field(min_length=1)
    dlc: str = Field(min_length=1)
    year: int = Field(ge=2016, le=2100)
    perk_1: str = Field(min_length=1)
    perk_2: str = Field(min_length=1)
    perk_3: str = Field(min_length=1)
    difficulty: Literal["Easy", "Intermediate", "Hard", "Very Hard"]
    power: str = Field(default="None")
    description: str = Field(min_length=1)
    image: Optional[str] = Field(default=None)
    movement_speed: str = Field(min_length=1)
    terror_radius: str = Field(min_length=1)
    height: str = Field(default="N/A")
    voice_actor: str = Field(min_length=1)


# ============================================================
# DATA
# ============================================================
characters = [
    {
        "id": 1,
        "name": "Dwight Fairfield",
        "character_code": "S01",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Crotus Prenn Asylum",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Bond",
        "perk_2": "Prove Thyself",
        "perk_3": "Leader",
        "difficulty": "Easy",
        "power": "None",
        "description": "A nervous leader whose perks help allies locate one another and increase team repair and action efficiency.",
        "image": "https://deadbydaylight.com/static/0fe15a5913b4d237f4e4f813e492cbba/fa99b/DBD_Survivor_Meg_only_5019ce4dbb.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Ian Chuprun (BHVR)"
    },
    {
        "id": 2,
        "name": "Meg Thomas",
        "character_code": "S02",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "MacMillan Estate",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Quick & Quiet",
        "perk_2": "Sprint Burst",
        "perk_3": "Adrenaline",
        "difficulty": "Easy",
        "power": "None",
        "description": "An energetic athlete capable of outrunning danger, vaulting silently, and escaping high-pressure chases.",
        "image": "https://deadbydaylight.com/static/0fe15a5913b4d237f4e4f813e492cbba/fa99b/DBD_Survivor_Meg_only_5019ce4dbb.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Ingrid Blemur (BHVR)"
    },
    {
        "id": 3,
        "name": "Claudette Morel",
        "character_code": "S03",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Canada",
        "realm": "Autohaven Wreckers",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Empathy",
        "perk_2": "Botany Knowledge",
        "perk_3": "Self-Care",
        "difficulty": "Easy",
        "power": "None",
        "description": "A studious botanist who uses her knowledge to heal herself and her teammates with high efficiency.",
        "image": "https://deadbydaylight.com/static/74aa57bab4337e239da486e69269b970/b66d6/DBD_Survivor_Claudette_only_92c9dc3504.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Sarah Robinson (BHVR)"
    },
    {
        "id": 4,
        "name": "Jake Park",
        "character_code": "S04",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Red Forest",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Iron Will",
        "perk_2": "Calm Spirit",
        "perk_3": "Saboteur",
        "difficulty": "Easy",
        "power": "None",
        "description": "A solitary survivalist capable of sabotaging meat hooks quietly and staying calm under intense pressure.",
        "image": "https://deadbydaylight.com/static/f48c2c6f50fe1d5a3a538668681d64ed/e86eb/DBD_Survivor_Jake_only_d11a2df75e.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Kevin Boissonneault (BHVR)"
    },
    {
        "id": 5,
        "name": "Nea Karlsson",
        "character_code": "S05",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Sweden",
        "realm": "Crotus Prenn Asylum",
        "dlc": "The Last Breath Chapter",
        "year": 2016,
        "perk_1": "Balanced Landing",
        "perk_2": "Urban Evasion",
        "perk_3": "Streetwise",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "An urban artist skilled in stealth, crouch-walking quickly, and landing safely from extreme heights.",
        "image": "https://deadbydaylight.com/static/1e954a7b4549ed626cac2f60ca2f1028/2df8f/DBD_Survivor_Nea_only_8dab36e01b.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Morgane Ravasi (BHVR)"
    },
    {
        "id": 6,
        "name": "Laurie Strode",
        "character_code": "S06",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Haddonfield",
        "dlc": "The Halloween Chapter",
        "year": 2016,
        "perk_1": "Sole Survivor",
        "perk_2": "Object of Obsession",
        "perk_3": "Decisive Strike",
        "difficulty": "Hard",
        "power": "None",
        "description": "A resilient survivor whose determination allows her to become the Killer's Obsession and break free from grasps.",
        "image": "https://static.wikia.nocookie.net/halloweenmovie/images/b/b9/LaurieDBD.webp/revision/latest?cb=20220402055032",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Catherine Lecours (BHVR)"
    },
    {
        "id": 7,
        "name": "Ace Visconti",
        "character_code": "S07",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Argentina",
        "realm": "Backwater Swamp",
        "dlc": "Of Flesh and Mud Chapter",
        "year": 2016,
        "perk_1": "Open-Handed",
        "perk_2": "Up the Ante",
        "perk_3": "Ace in the Hole",
        "difficulty": "Easy",
        "power": "None",
        "description": "A lucky gambler who boosts aura reading ranges and increases luck and chest add-on quality for the team.",
        "image": "https://deadbydaylight.com/static/b8d8bc40047189d8410df495e6691270/0005a/DBD_Survivor_Ace_only_f4ed90f604.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Sébastien Varas (BHVR)"
    },
    {
        "id": 8,
        "name": "William 'Bill' Overbeck",
        "character_code": "S08",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Left Behind Paragraph",
        "year": 2017,
        "perk_1": "Left Behind",
        "perk_2": "Borrowed Time",
        "perk_3": "Unbreakable",
        "difficulty": "Hard",
        "power": "None",
        "description": "A tough military veteran accustomed to sacrificing himself for the group and picking himself up from dying states.",
        "image": "https://deadbydaylight.com/static/25a713e5f0cb97ae95598346607788de/c3d2b/DBD_Survivor_William_Bill_only_b845ef6c74.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Ricardo Gomez (BHVR)"
    },
    {
        "id": 9,
        "name": "Feng Min",
        "character_code": "S09",
        "role": "Survivor",
        "gender": "Female",
        "origin": "China",
        "realm": "Léry's Memorial Institute",
        "dlc": "Spark of Madness Chapter",
        "year": 2017,
        "perk_1": "Technician",
        "perk_2": "Lithe",
        "perk_3": "Alert",
        "difficulty": "Easy",
        "power": "None",
        "description": "An esports competitor who repairs generators quietly, gains speed when vaulting, and tracks Killer actions.",
        "image": "https://deadbydaylight.com/static/64f24a9f3705db694aa68a2bd28d10d9/ad4ca/DBD_Survivor_Feng_Ming_only_a988940ff0.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Bianca Lavric (BHVR)"
    },
    {
        "id": 10,
        "name": "David King",
        "character_code": "S10",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United Kingdom",
        "realm": "Red Forest",
        "dlc": "A Lullaby for the Dark Chapter",
        "year": 2017,
        "perk_1": "We're Gonna Live Forever",
        "perk_2": "Dead Hard",
        "perk_3": "No Mither",
        "difficulty": "Hard",
        "power": "None",
        "description": "A rugged brawler who takes hits for his teammates, pushes through injuries, and withstands fatal blows.",
        "image": "https://deadbydaylight.com/static/37b607f85bcac74e5b7dd0ee159b4643/4421b/DBD_Survivor_David_King_only_92578775b6.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Stefan Horvath (BHVR)"
    },
    {
        "id": 11,
        "name": "Quentin Smith",
        "character_code": "S11",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Springwood",
        "dlc": "A Nightmare on Elm Street Chapter",
        "year": 2017,
        "perk_1": "Wake Up!",
        "perk_2": "Pharmacy",
        "perk_3": "Vigil",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "A sleepy survivor who opens exit gates faster, loots med-kits reliably, and reduces status effect durations.",
        "image": "https://deadbydaylight.com/static/0b2382adae76d6b79a394fdd0dce7404/0f2df/DBD_Survivor_Quentin_only_1ec65c154a.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Louis McLean (BHVR)"
    },
    {
        "id": 12,
        "name": "Detective David Tapp",
        "character_code": "S12",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Gideon Meat Plant",
        "dlc": "The SAW Chapter",
        "year": 2018,
        "perk_1": "Tenacity",
        "perk_2": "Detective's Intuition",
        "perk_3": "Stake Out",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "An obsessed detective who crawls quickly while recovering and tracks objective auras after generator completions.",
        "image": "https://deadbydaylight.com/static/1cd51fbdf2a23db9a1f73720e49662d4/1b615/DBD_Survivor_David_Tapp_only_372da5fad1.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Dave Blake (BHVR)"
    },
    {
        "id": 13,
        "name": "Kate Denson",
        "character_code": "S13",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Campbell's Chapel",
        "dlc": "Curtain Call Chapter",
        "year": 2018,
        "perk_1": "Dance With Me",
        "perk_2": "Windows of Opportunity",
        "perk_3": "Boil Over",
        "difficulty": "Easy",
        "power": "None",
        "description": "A hopeful songbird who tracks vault and pallet auras and fiercely resists being carried to hooks.",
        "image": "https://deadbydaylight.com/static/c19ceb6f87fdc19072ec9afb471bffde/43423/DBD_Survivor_Kate_only_a94e775efb.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Daphné Poulin Gourdeau (BHVR)"
    },
    {
        "id": 14,
        "name": "Adam Francis",
        "character_code": "S14",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Jamaica",
        "realm": "Yamaoka Estate",
        "dlc": "Shattered Bloodline Chapter",
        "year": 2018,
        "perk_1": "Diversion",
        "perk_2": "Deliverance",
        "perk_3": "Autodidact",
        "difficulty": "Hard",
        "power": "None",
        "description": "A resourceful teacher capable of distracting Killers with pebbles and unhooking himself securely.",
        "image": "https://deadbydaylight.com/static/d573cb5d078562279defa864f92865dc/8ada0/DBD_Survivor_Adam_only_b71e1ed1d8.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Bourbaki Joseph (BHVR)"
    },
    {
        "id": 15,
        "name": "Jeff Johansen",
        "character_code": "S15",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Canada",
        "realm": "Ormond",
        "dlc": "Darkness Among Us Chapter",
        "year": 2018,
        "perk_1": "Breakdown",
        "perk_2": "Aftercare",
        "perk_3": "Distortion",
        "difficulty": "Easy",
        "power": "None",
        "description": "A quiet artist whose perks break hooks upon escape, show team auras, and hide his own from the Killer.",
        "image": "https://deadbydaylight.com/static/fc98f794f4bc8fb3d3bf9739efa2cf48/12122/DBD_Survivor_Jeff_only_4c4caad581.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Filip Ivanovic (BHVR)"
    },
    {
        "id": 16,
        "name": "Jane Romero",
        "character_code": "S16",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "The Plague's Temple",
        "dlc": "Demise of the Faithful Chapter",
        "year": 2019,
        "perk_1": "Solidarity",
        "perk_2": "Poised",
        "perk_3": "Head On",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "An influential talk show host who heals while healing others, hides scratch marks on generator completions, and stuns Killers out of lockers.",
        "image": "https://deadbydaylight.com/static/363228a4ebced2a793845352cb86ac67/1852c/DBD_Survivor_Jane_only_4629ed580e.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Patricia Brochu-Gagné (BHVR)"
    },
    {
        "id": 17,
        "name": "Ash Williams",
        "character_code": "S17",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Ash vs Evil Dead Paragraph",
        "year": 2019,
        "perk_1": "Flip-Flop",
        "perk_2": "Buckle Up",
        "perk_3": "Mettle of Man",
        "difficulty": "Hard",
        "power": "None",
        "description": "A legendary demon hunter who converts recovery progress to wiggle progress and absorbs fatal blows.",
        "image": "https://deadbydaylight.com/static/f864b1820f2137a46144a3c46c533011/0fb44/DBD_Survivor_Ash_only_03e2a515fa.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Bruce Campbell (Original Actor)"
    },
    {
        "id": 18,
        "name": "Nancy Wheeler",
        "character_code": "S18",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Inner Strength",
        "perk_2": "Fixated",
        "perk_3": "Better Together",
        "difficulty": "Easy",
        "power": "None",
        "description": "A headstrong journalist who heals herself by cleansing totems, sees her own scratch marks, and highlights generators for nearby allies.",
        "image": "https://deadbydaylight.com/static/4c128ebcae087481f9a55f2ad8f4b5e2/71c80/CM_1639_DBD_Website_Ch13_Character_Page_Nancy_ONLY_8f259fd20e.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Madison Lee (Voice Actress)"
    },
    {
        "id": 19,
        "name": "Steve Harrington",
        "character_code": "S19",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Babysitter",
        "perk_2": "Camaraderie",
        "perk_3": "Second Wind",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "A protective former popular kid who pauses hook struggle timers and hides unhooked teammates' pools of blood and scratch marks.",
        "image": "https://deadbydaylight.com/static/6b9c65a52cef3e1f7ea7ad9e68870f02/f5268/CM_1639_DBD_Website_Ch13_Character_Page_Steve_ONLY_f87506bf77.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Undisclosed Voice Actor"
    },
    {
        "id": 20,
        "name": "Yui Kimura",
        "character_code": "S20",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Cursed Legacy Chapter",
        "year": 2019,
        "perk_1": "Lucky Break",
        "perk_2": "Any Means Necessary",
        "perk_3": "Breakout",
        "difficulty": "Easy",
        "power": "None",
        "description": "A hardened street racer who resets dropped pallets, hides her pools of blood when injured, and aids wiggling allies.",
        "image": "https://deadbydaylight.com/static/915a04bc5882f32ab2e6e74f99568f85/1c3db/DBD_Survivor_Yui_Kamura_only_fcfa8c6786.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Daniela Pinto (BHVR)"
    },
    {
        "id": 21,
        "name": "Zarina Kassir",
        "character_code": "S21",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Lebanon",
        "realm": "Grave of Glenvale",
        "dlc": "Chains of Hate Chapter",
        "year": 2020,
        "perk_1": "Off the Record",
        "perk_2": "Red Herring",
        "perk_3": "For the People",
        "difficulty": "Hard",
        "power": "None",
        "description": "An independent filmmaker capable of instantly healing others at her own expense and masking her aura after being unhooked.",
        "image": "https://deadbydaylight.com/static/647ba234e9c9806c0783453bb0373247/5b0f6/DBD_Survivor_Zarina_only_404279f793.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Émilie Paquin (BHVR)"
    },
    {
        "id": 22,
        "name": "Cheryl Mason",
        "character_code": "S22",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Midwich Elementary School",
        "dlc": "Silent Hill Chapter",
        "year": 2020,
        "perk_1": "Soul Guard",
        "perk_2": "Blood Pact",
        "perk_3": "Repressed Alliance",
        "difficulty": "Hard",
        "power": "None",
        "description": "A resilient young woman who blocks generators from the Killer's regression using the Entity and gains endurance after healing.",
        "image": "https://deadbydaylight.com/static/2efda55012428f36ea64fd987d446cfe/a3edc/DBD_Survivor_Cheryl_only_2b098e322c.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Undisclosed Voice Actress"
    },
    {
        "id": 23,
        "name": "Felix Richter",
        "character_code": "S23",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Germany",
        "realm": "Undisclosed",
        "dlc": "Descend Beyond Chapter",
        "year": 2020,
        "perk_1": "Visionary",
        "perk_2": "Desperate Measures",
        "perk_3": "Built to Last",
        "difficulty": "Easy",
        "power": "None",
        "description": "A brilliant architect who refills depleted item charges inside lockers and gains speed boosts to actions based on injured allies.",
        "image": "https://deadbydaylight.com/static/e4f7bbde54b1571c7d3e4122f0de8d7e/315f4/DBD_Survivor_Felix_only_a3f9dddd83.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Frédéric Poirier (BHVR)"
    },
    {
        "id": 24,
        "name": "Élodie Rakoto",
        "character_code": "S24",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Madagascar",
        "realm": "Undisclosed",
        "dlc": "A Binding of Kin Chapter",
        "year": 2020,
        "perk_1": "Appraisal",
        "perk_2": "Deception",
        "perk_3": "Power Struggle",
        "difficulty": "Hard",
        "power": "None",
        "description": "An occult investigator who rummages through opened chests, fakes locker entries, and drops pallets on the Killer while being carried.",
        "image": "https://deadbydaylight.com/static/d24ddf5d55c8ee3bb7d5da18c155bc63/d3b07/DBD_Survivor_Elodie_only_61b051f9db.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Beatrix Moersch (BHVR)"
    },
    {
        "id": 25,
        "name": "Yun-Jin Lee",
        "character_code": "S25",
        "role": "Survivor",
        "gender": "Female",
        "origin": "South Korea",
        "realm": "All-Kill Realm",
        "dlc": "All-Kill Chapter",
        "year": 2021,
        "perk_1": "Fast Track",
        "perk_2": "Smash Hit",
        "perk_3": "Self-Preservation",
        "difficulty": "Easy",
        "power": "None",
        "description": "A self-serving music producer who benefits from her teammates' misfortunes, gaining generator tokens and sprint bursts from pallet stuns.",
        "image": "https://deadbydaylight.com/static/b38895e1b5c2b0807af564b00908b1ff/99ebe/DBD_Survivor_Yun_Jin_only_ad2b67d501.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "So-Hee Kim (Voice Actor)"
    },
    {
        "id": 26,
        "name": "Jill Valentine",
        "character_code": "S26",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Counterforce",
        "perk_2": "Resurgence",
        "perk_3": "Blast Mine",
        "difficulty": "Easy",
        "power": "None",
        "description": "An elite police operative who cleanses totems rapidly, regains instant healing progress upon unhooking, and traps generators with blinding mines.",
        "image": "https://deadbydaylight.com/static/11142a038069d83025fdb2d1215ce96a/a5a4c/DBD_Survivor_Jill_only_6add07fd37.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Chaney Crabb (The Monster Factory)"
    },
    {
        "id": 27,
        "name": "Leon S. Kennedy",
        "character_code": "S27",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Bite the Bullet",
        "perk_2": "Flashbang",
        "perk_3": "Rookie Spirit",
        "difficulty": "Easy",
        "power": "None",
        "description": "An idealistic rookie cop who completely silences his healing sounds and crafts blinding flashbang grenades inside lockers.",
        "image": "https://deadbydaylight.com/static/9756c3a8ceed79cf76cbe28f96fc039f/4a362/DBD_Survivor_Leon_only_83e8e83493.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Riley McShane (The Monster Factory)"
    },
    {
        "id": 28,
        "name": "Mikaela Reid",
        "character_code": "S28",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Hour of the Witch Chapter",
        "year": 2021,
        "perk_1": "Clairvoyance",
        "perk_2": "Boon: Circle of Healing",
        "perk_3": "Boon: Shadow Step",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "A modern witch who blesses totems to create areas where survivors can heal quickly and hide their scratch marks.",
        "image": "https://deadbydaylight.com/static/38b6b06bcd8f4629c7ed3784f8872cfd/2f542/DBD_Survivor_Mikaela_only_3e3b90279b.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Adrienne Cowan (The Monster Factory)"
    },
    {
        "id": 29,
        "name": "Jonah Vasquez",
        "character_code": "S29",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Eyrie of Crows",
        "dlc": "Portrait of a Murder Chapter",
        "year": 2021,
        "perk_1": "Overcome",
        "perk_2": "Corrective Action",
        "perk_3": "Boon: Exponential",
        "difficulty": "Easy",
        "power": "None",
        "description": "A brilliant codebreaker who extends hit speed bursts and creates a recovery oasis for downed allies using Boon totems.",
        "image": "https://deadbydaylight.com/static/a187b5b028cb0a23a7e6228dcbc68e29/944ed/DBD_Survivor_Jonah_only_214fe0fc2f.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Felipe Quinzaños (The Monster Factory)"
    },
    {
        "id": 30,
        "name": "Yoichi Asakawa",
        "character_code": "S30",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Japan",
        "realm": "Base Game",
        "dlc": "Sadako Rising Chapter",
        "year": 2022,
        "perk_1": "Parental Guidance",
        "perk_2": "Empathic Connection",
        "perk_3": "Boon: Dark Theory",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "A psychic marine biologist who completely hides blood, scratches, and grunts after stunning a killer, and blesses totems to grant speed boosts.",
        "image": "https://deadbydaylight.com/static/e83583da80436b24b6ce4f497f56e31e/a6472/DBD_Survivor_Yoichi_only_67e6855e29.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Mirai Kawashima (The Monster Factory)"
    },
    {
        "id": 31,
        "name": "Haddie Kaur",
        "character_code": "S31",
        "role": "Survivor",
        "gender": "Female",
        "origin": "India",
        "realm": "Garden of Joy",
        "dlc": "Roots of Dread Chapter",
        "year": 2022,
        "perk_1": "Inner Focus",
        "perk_2": "Residual Manifest",
        "perk_3": "Overzealous",
        "difficulty": "Easy",
        "power": "None",
        "description": "A psychic podcaster who sees nearby ally scratch marks, blinds Killers to inflict blindness, and increases repair speed after cleansing totems.",
        "image": "https://deadbydaylight.com/static/4db50dcec74a704f235259d8847f47e2/5fed0/DBD_Survivor_Haddie_only_c03e10dcd0.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Ashavari Anna Joshi (The Monster Factory)"
    },
    {
        "id": 32,
        "name": "Ada Wong",
        "character_code": "S32",
        "role": "Survivor",
        "gender": "Female",
        "origin": "China",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Wiretap",
        "perk_2": "Reactive Healing",
        "perk_3": "Low Profile",
        "difficulty": "Easy",
        "power": "None",
        "description": "A secretive spy who installs camera wiretaps on generators, heals instantly when nearby allies are hit, and hides traces when the lone survivor.",
        "image": "https://deadbydaylight.com/static/c50f82b1434e9e777754d09e467ec0cf/82f4a/DBD_Survivor_Ada_Wong_only_5a1367612e.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Vicky Psarakis (The Monster Factory)"
    },
    {
        "id": 33,
        "name": "Rebecca Chambers",
        "character_code": "S33",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Better Than New",
        "perk_2": "Hyperfocus",
        "perk_3": "Reassurance",
        "difficulty": "Hard",
        "power": "None",
        "description": "A young prodigy medic who pauses the sacrifice timer of hooked allies and rewards rapid consecutive Great Skill Checks with huge repair bursts.",
        "image": "https://deadbydaylight.com/static/44a306f9dd69bba3c8dd77b5298070b9/4e40a/DBD_Survivor_Rebeca_only_b6a6753e9b.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Megan Orvold-Scheider (The Monster Factory)"
    },
    {
        "id": 34,
        "name": "Vittorio Toscano",
        "character_code": "S34",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Italy",
        "realm": "The Shattered Square",
        "dlc": "Forged in Fog Chapter",
        "year": 2022,
        "perk_1": "Potential Energy",
        "perk_2": "Fogwise",
        "perk_3": "Quick Gambit",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "An ancient, arcane scholar who stores generator progression to instantly dump it elsewhere and reveals the Killer during Great Skill Checks.",
        "image": "https://deadbydaylight.com/static/8cd8121c9f773a21c7f17ae85d5d7d23/aff4d/DBD_Survivor_Vittorio_only_4848b4923b.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Luc de Villars (The Monster Factory)"
    },
    {
        "id": 35,
        "name": "Thalita Lyra",
        "character_code": "S35",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Brazil",
        "realm": "Shelter Woods",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "Cut Loose",
        "perk_2": "Friendly Competition",
        "perk_3": "Teamwork: Power of Two",
        "difficulty": "Easy",
        "power": "None",
        "description": "A community-focused kite fighter whose perks reward group generator repairs and synchronized vault maneuvers during chases.",
        "image": "https://deadbydaylight.com/static/6cdb99c07fcc2f22b3333bea19e48530/ea2f7/DBD_Survivor_Thalita_only_5d556e7020.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Sylvia Salustti (Brazilian Voice Actress)"
    },
    {
        "id": 36,
        "name": "Renato Lyra",
        "character_code": "S36",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Brazil",
        "realm": "Shelter Woods",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "Blood Rush",
        "perk_2": "Background Player",
        "perk_3": "Teamwork: Collective Stealth",
        "difficulty": "Hard",
        "power": "None",
        "description": "A calm analyst who activates massive sprint bursts when the killer picks up an ally and can force exhaustion recovery at the cost of health.",
        "image": "https://deadbydaylight.com/static/2d0ab948e475fc1fb44858a560bd9966/33492/DBD_Survivor_Renato_only_cd4eb78666.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Felipe Grinnan (Brazilian Voice Actor)"
    },
    {
        "id": 37,
        "name": "Gabriel Soma",
        "character_code": "S37",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Undisclosed",
        "realm": "Toba Landing",
        "dlc": "End Transmission Chapter",
        "year": 2023,
        "perk_1": "Troubleshooter",
        "perk_2": "Made for This",
        "perk_3": "Scavenger",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "A cloned starship technician who runs faster when injured, reveals the highest-progress generator during chases, and recycles depleted toolboxes.",
        "image": "https://deadbydaylight.com/static/d7941b67057e857981d0ebd9b55dde5a/c0840/CM_1285_DBD_Website_Ch27_Character_Page_Survivor_Gabriel_ONLY_1d66e2e05e.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Stevie Boiser (The Monster Factory)"
    },
    {
        "id": 38,
        "name": "Nicolas Cage",
        "character_code": "S38",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Nicolas Cage Paragraph",
        "year": 2023,
        "perk_1": "Dramaturgy",
        "perk_2": "Scene Partner",
        "perk_3": "Plot Twist",
        "difficulty": "Hard",
        "power": "None",
        "description": "An eccentric movie superstar who can scream to read killer auras, fake his own death to completely heal from the dying state, and gain random items.",
        "image": "https://deadbydaylight.com/static/207bcdca864bfebdd18949e565e13867/fadb4/CM_1489_DBD_Website_Ch28_5_Character_Page_Survivor_Nick_Cage_ONLY_f3160126ef.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Nicolas Cage"
    },
    {
        "id": 39,
        "name": "Ellen Ripley",
        "character_code": "S39",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Nostromo Wreckage",
        "dlc": "Alien Chapter",
        "year": 2023,
        "perk_1": "Lucky Star",
        "perk_2": "Chemical Trap",
        "perk_3": "Light-Footed",
        "difficulty": "Easy",
        "power": "None",
        "description": "An iron-willed space survivor who suppresses her footsteps while healthy and installs slowing chemical traps onto dropped pallets.",
        "image": "https://deadbydaylight.com/static/5abb04054e04b4b184a98ced0a4f25fc/83653/CM_1549_DBD_Character_Render_Survivor_Ellen_18e40d4323.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Molly Daisy (The Monster Factory)"
    },
    {
        "id": 40,
        "name": "Alan Wake",
        "character_code": "S40",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Alan Wake Chapter",
        "year": 2024,
        "perk_1": "Champion of Light",
        "perk_2": "Boon: Illumination",
        "perk_3": "Deadline",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "A tormented writer who runs faster while shining flashlights, inflicts slowed movement on blinded killers, and alters skill check frequencies.",
        "image": "https://deadbydaylight.com/static/4e16e064f9f2888a3ef27202bc256e43/aa26e/DBD_Chap30_5_Zodiac_Character_Renders_Survivor_3b678c2a9a.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Matthew Porretta (Original Voice Actor)"
    },
    {
        "id": 41,
        "name": "Sable Ward",
        "character_code": "S41",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Forgotten Ruins",
        "dlc": "All Things Wicked Chapter",
        "year": 2024,
        "perk_1": "Invocation: Weaving Spiders",
        "perk_2": "Strength in Shadows",
        "perk_3": "Wicked",
        "difficulty": "Hard",
        "power": "None",
        "description": "A gothic alternative girl who performs dark invocations inside the basement to trade her health for permanent match-wide generator repair progress.",
        "image": "https://deadbydaylight.com/static/18f59ffadbe3fa28c1d170a4960ea260/dbd1f/DBD_Website_Ch31_Character_Page_Survivor_Sable_084678d1f0.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Liz Morey (Professional Voice Actress)"
    },
    {
        "id": 42,
        "name": "Aestri Yazar",
        "character_code": "S42",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Faerûn",
        "realm": "Forgotten Ruins",
        "dlc": "Dungeons & Dragons Chapter",
        "year": 2024,
        "perk_1": "Mirrored Illusion",
        "perk_2": "Bardic Inspiration",
        "perk_3": "Still Sight",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "An elven bard who casts illusory copies of herself on objectives and plays dice roll musical melodies to boost team performance.",
        "image": "https://deadbydaylight.com/static/ee95eb716d9e9ee9256126b11270a284/b0d5c/DBD_Website_Ch31_Character_Page_Survivor_Aestri_ONLY_0d4f73719b.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Aestri: Jesse Vilinsky; Baermar: Robbie Daymond"
    },
    {
        "id": 43,
        "name": "Lara Croft",
        "character_code": "S43",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United Kingdom",
        "realm": "Base Game",
        "dlc": "Tomb Raider Chapter",
        "year": 2024,
        "perk_1": "Finesse",
        "perk_2": "Hardened",
        "perk_3": "Specialist",
        "difficulty": "Easy",
        "power": "None",
        "description": "A legendary archaeologist who executes high-speed window vaults while healthy, bypasses screams, and permanently drops max generator requirements.",
        "image": "https://deadbydaylight.com/static/14ec5edaf1680a41f9db353056227255/44bb7/WEB_DBD_DONUTS_Survivor_Lara_only_c83551f39a.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Emily O'Brien (Voice Actress)"
    },
    {
        "id": 44,
        "name": "Trevor Belmont",
        "character_code": "S44",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Wallachia",
        "realm": "Castle Dracula",
        "dlc": "Castlevania Chapter",
        "year": 2024,
        "perk_1": "Eyes of Belmont",
        "perk_2": "Exultation",
        "perk_3": "Moment of Glory",
        "difficulty": "Easy",
        "power": "None",
        "description": "A battle-hardened monster hunter who extends killer aura reveal durations and upgrades his current item tier upon stunning the killer.",
        "image": "https://deadbydaylight.com/static/1b26554ebecb0d0c4ecc9e43eca418b2/8634a/DBD_ECLAIR_WEBPAGE_Character_Page_Survivor_Trevor_ONLY_5c3deb1b56.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Andrew Wheildon-Dennis (Voice Actor)"
    },
    {
        "id": 45,
        "name": "Rick Grimes",
        "character_code": "S47",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "None",
        "dlc": "Chapter 34.5: The Walking Dead",
        "year": 2025,
        "perk_1": "Apocalyptic Ingenuity",
        "perk_2": "Come and Get Me!",
        "perk_3": "Teamwork: Toughen Up",
        "difficulty": "Hard",
        "power": "None",
        "description": "A tactical former sheriff who crafts fragile temporary replacement pallets out of destroyed loops and draws killer aggro away from injured team members.",
        "image": "https://deadbydaylight.com/static/249e148bb87d0ddb393b2815caa2c4ab/d5ea7/Db_D_LASAGNA_CH_Character_Art_Survivor_S47_WEB_3840_X1344_VF_2_Character_only_d19bdfa143.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Andrew Lincoln"
    },
    {
        "id": 46,
        "name": "Michonne",
        "character_code": "S48",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "None",
        "dlc": "Chapter 34.5: The Walking Dead",
        "year": 2025,
        "perk_1": "Conviction",
        "perk_2": "Last Stand",
        "perk_3": "Teamwork: Throw Down",
        "difficulty": "Hard",
        "power": "None",
        "description": "A fearless katana survivor who triggers high-stakes, single-use window stuns, picks herself up from the dying state, and grants defensive buffs.",
        "image": "https://deadbydaylight.com/static/3049fe32c32188db2d9de7d3b8982886/58672/Db_D_LASAGNA_CH_Character_Art_Survivor_S48_WEB_3840_X1344_V_Fb_Character_only_98ff606a16.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Erikka J. (Voice Actress)"
    },
    {
        "id": 47,
        "name": "Vee Boonyasak",
        "character_code": "S49",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Thailand",
        "realm": "None",
        "dlc": "Chapter 36.5: Sinister Grace",
        "year": 2025,
        "perk_1": "Road Life",
        "perk_2": "ONE-TWO-THREE-FOUR!",
        "perk_3": "Ghost Notes",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "An energetic punk rock drummer who utilizes rhythm performance actions to trigger team skill check bursts and slips out of loops with advanced stealth.",
        "image": "https://deadbydaylight.com/static/69acdd3cb30f83ee0a48bd0a15a0e732/88c81/DBD_MAPLE_CH_WEB_CHARACTERPAGE_SURVIVOR_Vee_098b4a177e.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Sura Siu (Voice-Over Artist)"
    },
    {
        "id": 48,
        "name": "Aurora Stardotter",
        "character_code": "S50",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Terra Primus",
        "realm": "None",
        "dlc": "Chapter 38: Chorus of Sin",
        "year": 2026,
        "perk_1": "Starlight Beacon",
        "perk_2": "Cosmic Link",
        "perk_3": "Astral Projection",
        "difficulty": "Hard",
        "power": "None",
        "description": "An otherworldly astronaut who marks physical navigation points on the map and channels short distances to pass directly through solid tile walls.",
        "image": "https://deadbydaylight.com/static/ac13b9b590f6f406796835634e60fee8/ca5bd/DBD_UDON_CHAPTER_STAND_ALONE_RENDERS_WEB_ASSETS_AURORA_CHARACTER_ONLY_2163848678.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Claire Vousden (Voice Actress)"
    },
    {
        "id": 49,
        "name": "Dustin Henderson",
        "character_code": "S51",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Hawkins",
        "dlc": "Stranger Things Chapter",
        "year": 2025,
        "perk_1": "BADA BADA BOOM",
        "perk_2": "Change Of Plan",
        "perk_3": "Teamwork: Soft Spoken",
        "difficulty": "Intermediate",
        "power": "None",
        "description": "Clever and loyal to a fault, Dustin Hendersen has saved his group more time than he can count.",
        "image": "https://deadbydaylight.com/static/7c0009ce5812866c62919b5f7a15dfb0/3b120/DBD_WEBPAGE_Character_Page_DUSTIN_CHARACTER_ONLY_1b12c7a603.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Jacob Craner (Voice Actor)"
    },
    {
        "id": 50,
        "name": "Eleven",
        "character_code": "S52",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "hawkins",
        "dlc": "Stranger Things Chapter",
        "year": 2025,
        "perk_1": "Extracensory Perception",
        "perk_2": "We See You",
        "perk_3": "Oasis Refresh",
        "difficulty": "Easy",
        "power": "None",
        "description": "Raised in captivity and studied for her psychic abilities, the lonely girl called Eleven never experienced a meaningful connection",
        "image": "https://deadbydaylight.com/static/2a03b828a4986c03a59f3d3749604ee8/8834d/DBD_POUTINE_WEBPAGE_Character_Page_ELEVEN_VF_2_Character_Only_e8f307c7a5.webp",
        "movement_speed": "4.0",
        "terror_radius": "N/A",
        "height": "N/A",
        "voice_actor": "Abby Espiritu (Voice Actress)"
    },
    {
        "id": 51,
        "name": "The Trapper",
        "character_code": "K01",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "MacMillan Estate",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Unnerving Presence",
        "perk_2": "Brutal Strength",
        "perk_3": "Agitation",
        "difficulty": "Easy",
        "power": "Bear Trap",
        "description": "An area-control killer who sets hidden, physical steel bear traps across the map to catch, damage, and immobilize unwary survivors.",
        "image": "https://deadbydaylight.com/static/0a16e1db54f6c959580370679235eefb/7f738/DBD_Killer_Trapper_only_335b9655b2.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Filip Ivanovic (BHVR)"
    },
    {
        "id": 52,
        "name": "The Wraith",
        "character_code": "K02",
        "role": "Killer",
        "gender": "Male",
        "origin": "Nigeria",
        "realm": "Autohaven Wreckers",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Predator",
        "perk_2": "Bloodhound",
        "perk_3": "Shadowborn",
        "difficulty": "Easy",
        "power": "Wailing Bell",
        "description": "A stealth killer who rings a mystical bell to turn completely invisible, allowing him to traverse the map swiftly and ambush survivors.",
        "image": "https://deadbydaylight.com/static/8dd6b13f4343ca2e6b072f91b0f30308/04af3/DBD_Killer_Wraith_only_23c19dc579.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Filip Ivanovic (BHVR)"
    },
    {
        "id": 53,
        "name": "The Hillbilly",
        "character_code": "K03",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Coldwind Farm",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Enduring",
        "perk_2": "Lightborn",
        "perk_3": "Tinkerer",
        "difficulty": "Easy",
        "power": "Chainsaw Sprint",
        "description": "A high-mobility, high-threat killer who charges forward at high speeds with his chainsaw, instantly downing any survivor caught in his path.",
        "image": "https://deadbydaylight.com/static/b2296c4b7485cabc0b79cc205fc14b13/60045/DBD_Killer_Hillbilly_only_e3d5fe3977.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Filip Ivanovic (BHVR)"
    },
    {
        "id": 54,
        "name": "The Nurse",
        "character_code": "K04",
        "role": "Killer",
        "gender": "Female",
        "origin": "United Kingdom",
        "realm": "Crotus Prenn Asylum",
        "dlc": "The Last Breath Chapter",
        "year": 2016,
        "perk_1": "A Nurse's Calling",
        "perk_2": "Stridor",
        "perk_3": "Thanatophobia",
        "difficulty": "Very Hard",
        "power": "Spencer's Last Breath",
        "description": "A hyper-lethal teleporting killer who blinks directly through solid obstacles and walls to immediately strike fleeing survivors.",
        "image": "https://deadbydaylight.com/static/b327d72cd084f3f3f0d3ba02e2d369b4/61ef0/DBD_Killer_Nurse_only_fead4a1990.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Anais Renevey (BHVR)"
    },
    {
        "id": 55,
        "name": "The Shape",
        "character_code": "K05",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Haddonfield",
        "dlc": "The Halloween Chapter",
        "year": 2016,
        "perk_1": "Save the Best for Last",
        "perk_2": "Play with Your Food",
        "perk_3": "Dying Light",
        "difficulty": "Intermediate",
        "power": "Evil Within",
        "description": "An imposing stalker killer (Michael Myers) who watches survivors from afar to charge his inner malice, granting permanent stat tiers and instant-down capabilities.",
        "image": "https://deadbydaylight.wiki.gg/images/thumb/New_Store_Shape.png/1200px-New_Store_Shape.png?2d776e",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Frédéric Poirier (BHVR)"
    },
    {
        "id": 56,
        "name": "The Hag",
        "character_code": "K06",
        "role": "Killer",
        "gender": "Female",
        "origin": "Undisclosed",
        "realm": "Backwater Swamp",
        "dlc": "Of Flesh and Mud Chapter",
        "year": 2016,
        "perk_1": "Hex: The Third Seal",
        "perk_2": "Hex: Ruin",
        "perk_3": "Hex: Devour Hope",
        "difficulty": "Intermediate",
        "power": "Phantasm Traps",
        "description": "A tactical teleportation killer who draws mud traps on the ground, warping straight to their position whenever a survivor triggers them by walking.",
        "image": "https://deadbydaylight.com/static/eb104dc89d97177666f957ba9c60675b/c187b/DBD_Killer_Hag_only_d49168367b.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Eliane Pregent"
    },
    {
        "id": 57,
        "name": "The Doctor",
        "character_code": "K07",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Léry's Memorial Institute",
        "dlc": "Spark of Madness Chapter",
        "year": 2017,
        "perk_1": "Overwhelming Presence",
        "perk_2": "Monitor & Abuse",
        "perk_3": "Overcharge",
        "difficulty": "Easy",
        "power": "Carter's Spark",
        "description": "An oppressive disruption killer who releases localized madness shockwaves, driving survivors insane to reveal their locations and block interactions.",
        "image": "https://deadbydaylight.com/static/5a1d801090435633f93d3449ac0a6471/5bbf2/DBD_Killer_Doctor_only_dbafb9a311.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Alex Lin (BHVR)"
    },
    {
        "id": 58,
        "name": "The Huntress",
        "character_code": "K08",
        "role": "Killer",
        "gender": "Female",
        "origin": "Russia",
        "realm": "Red Forest",
        "dlc": "A Lullaby for the Dark Chapter",
        "year": 2017,
        "perk_1": "Beast of Prey",
        "perk_2": "Territorial Imperative",
        "perk_3": "Hex: Huntress Lullaby",
        "difficulty": "Intermediate",
        "power": "Hunting Hatchets",
        "description": "A deadly ranged killer who hurls sharp hatchets across loops and open maps, injuring or downing survivors from afar.",
        "image": "https://deadbydaylight.com/static/f00176036126f7f53d2944c863882ab9/e3912/DBD_Killer_Huntress_only_7510a188be.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Amélie Leguiader (BHVR)"
    },
    {
        "id": 59,
        "name": "The Cannibal",
        "character_code": "K09",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Leatherface Paragraph",
        "year": 2017,
        "perk_1": "Knock Out",
        "perk_2": "Barbecue & Chili",
        "perk_3": "Franklin's Demise",
        "difficulty": "Easy",
        "power": "Bubba's Chainsaw",
        "description": "A close-quarters threat killer (Leatherface) who swings his chainsaw in a wide, multi-hit sweeping tantrum, instantly downing any clusters of survivors.",
        "image": "https://deadbydaylight.com/static/1b68cdf1dd6c262332c572c0648d9e55/3f3fe/DBD_Killer_Cannibal_Leatherface_only_a4f6f2ed64.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Filip Ivanovic (BHVR)"
    },
    {
        "id": 60,
        "name": "The Nightmare",
        "character_code": "K10",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Springwood",
        "dlc": "A Nightmare on Elm Street Chapter",
        "year": 2017,
        "perk_1": "Fire Up",
        "perk_2": "Remember Me",
        "perk_3": "Blood Warden",
        "difficulty": "Easy",
        "power": "Dream Demon",
        "description": "A surreal dreamscape killer (Freddy Krueger) who pulls survivors into a sleeping state, allowing him to teleport directly to generators and lay slowing blood traps.",
        "image": "https://deadbydaylight.com/static/d89551facdb494b7bf07bf152bdeb510/03c7d/DBD_Killer_Nighmare_only_23c0774f8a.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Filip Ivanovic (BHVR)"
    },
    {
        "id": 61,
        "name": "The Pig",
        "character_code": "K11",
        "role": "Killer",
        "gender": "Female",
        "origin": "United States",
        "realm": "Gideon Meat Plant",
        "dlc": "The SAW Chapter",
        "year": 2018,
        "perk_1": "Hangman's Trick",
        "perk_2": "Surveillance",
        "perk_3": "Make Your Choice",
        "difficulty": "Easy",
        "power": "Jigsaw's Baptism",
        "description": "A stealthy ambush killer (Amanda Young) who crouches to remove her terror radius, lunges out from corners, and places ticking Reverse Bear Traps on downed survivors.",
        "image": "https://deadbydaylight.com/static/5368608f638bb795cebec319c929e767/12c29/DBD_Killer_Pig_Amanda_only_5e01155e0f.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Christine Marsh (BHVR)"
    },
    {
        "id": 62,
        "name": "The Clown",
        "character_code": "K12",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Crotus Prenn Asylum",
        "dlc": "Curtain Call Chapter",
        "year": 2018,
        "perk_1": "The Third Seal",
        "perk_2": "Coulrophobia",
        "perk_3": "Pop Goes the Weasel",
        "difficulty": "Easy",
        "power": "The Afterpiece Tonic",
        "description": "A tactical anti-loop killer who throws bottles of toxic gas to blur visions and slow down survivors, while deploying yellow gas to speed up his own chases.",
        "image": "https://deadbydaylight.com/static/b6629de77d94f595b115f99f031a421e/8d0aa/DBD_Killer_Clown_only_266fa0018c.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Sébastien Duval (BHVR)"
    },
    {
        "id": 63,
        "name": "The Spirit",
        "character_code": "K13",
        "role": "Killer",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Shattered Bloodline Chapter",
        "year": 2018,
        "perk_1": "Spirit Fury",
        "perk_2": "Hex: Haunted Ground",
        "perk_3": "Rancor",
        "difficulty": "Hard",
        "power": "Yamaoka's Haunting",
        "description": "A mind-game killer who detaches from her physical shell to travel invisibly through the spirit plane, tracking survivors purely via audio cues and scratch marks.",
        "image": "https://deadbydaylight.com/static/0b2f9f0e0198dce197e013af0e0522ce/6a87c/DBD_Killer_Spirit_only_ca6f40fdfa.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Gabrielle Murphy (BHVR)"
    },
    {
        "id": 64,
        "name": "The Legion",
        "character_code": "K14",
        "role": "Killer",
        "gender": "Group",
        "origin": "Canada",
        "realm": "Ormond",
        "dlc": "Darkness Among Us Chapter",
        "year": 2018,
        "perk_1": "Discordance",
        "perk_2": "Madness",
        "perk_3": "Iron Maiden",
        "difficulty": "Easy",
        "power": "Feral Frenzy",
        "description": "A fast-paced hit-and-run killer squad that sprint vaults over windows and pallets to rapidly stab multiple survivors, applying the bleeding Deep Wound status.",
        "image": "https://deadbydaylight.com/static/bc74d8d8211446710efd92be4a9fca00/84c23/DBD_Killer_Legion_only_0868f7f5e9.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Julie/Susie: Emilie Deschamps (BHVR); Frank/Joey: Nicolas Brassard (BHVR)"
    },
    {
        "id": 65,
        "name": "The Plague",
        "character_code": "K15",
        "role": "Killer",
        "gender": "Female",
        "origin": "Babylon",
        "realm": "Plague Realm",
        "dlc": "Demise of the Faithful Chapter",
        "year": 2019,
        "perk_1": "Corrupt Intervention",
        "perk_2": "Infectious Fright",
        "perk_3": "Dark Devotion",
        "difficulty": "Intermediate",
        "power": "Vile Purge",
        "description": "A systematic affliction killer who vomits contagious bile onto objects and survivors, forcing them into a permanently broken, vomiting, and trackable state.",
        "image": "https://deadbydaylight.com/static/2c332894590eb9a0dbf89e3c2c6d8400/222ac/DBD_Killer_Plague_only_418a9c3f53.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Undisclosed Voice Actress"
    },
    {
        "id": 66,
        "name": "The Ghost Face",
        "character_code": "K16",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Ghost Face Paragraph",
        "year": 2019,
        "perk_1": "I'm All Ears",
        "perk_2": "Thrilling Tremors",
        "perk_3": "Furtive Chase",
        "difficulty": "Easy",
        "power": "Night Shroud",
        "description": "A methodical stealth killer who hides his red stain and terror radius completely, leaning around corners to stalk and expose individual survivors.",
        "image": "https://deadbydaylight.com/static/57467dbd8c49b9983ba369ba74c25652/664d8/DBD_Killer_Ghostface_only_1702579267.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Filip Ivanovic (Art Director)"
    },
    {
        "id": 67,
        "name": "The Demogorgon",
        "character_code": "K17",
        "role": "Killer",
        "gender": "Male",
        "origin": "The Upside Down",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Surge",
        "perk_2": "Cruel Limits",
        "perk_3": "Mindbreaker",
        "difficulty": "Intermediate",
        "power": "Of the Abyss",
        "description": "A monstrous apex predator that lunges long distances across loops to shred pallets and tears open organic ground portals to travel under the map.",
        "image": "https://deadbydaylight.com/static/c42f4f5e440caf1d000a5e829db8d234/22fcf/CM_1639_DBD_Website_Ch13_Character_Page_Demogordon_ONLY_4c396614fc.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "None (various digitally processed sounds)"
    },
    {
        "id": 68,
        "name": "The Oni",
        "character_code": "K18",
        "role": "Killer",
        "gender": "Male",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Cursed Legacy Chapter",
        "year": 2019,
        "perk_1": "Zanshin Tactics",
        "perk_2": "Blood Echo",
        "perk_3": "Nemesis",
        "difficulty": "Hard",
        "power": "Yamaoka's Wrath",
        "description": "A high-momentum snowball killer who absorbs glowing blood orbs dropped by injured survivors to trigger a raging state, gaining map-wide dash speeds and lethal clubs.",
        "image": "https://deadbydaylight.com/static/eb970e766a7c9afbf0de6446f192a9d5/7e76c/DBD_Killer_Oni_only_0229974851.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Jean-Baptiste Garnier (BHVR)"
    },
    {
        "id": 69,
        "name": "The Deathslinger",
        "character_code": "K19",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Grave of Glenvale",
        "dlc": "Chains of Hate Chapter",
        "year": 2020,
        "perk_1": "Gearhead",
        "perk_2": "Dead Man's Switch",
        "perk_3": "Hex: Retribution",
        "difficulty": "Intermediate",
        "power": "The Redeemer",
        "description": "An inventive ranged killer who fires a mechanical harpoon gun to impale survivors, reeling them in closer across obstacles for a basic attack blow.",
        "image": "https://deadbydaylight.com/static/19d0fe628ace98ffe58686d956af6397/52d66/DBD_Killer_Deathslinger_only_ffbf514957.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Patrick Harris (BHVR)"
    },
    {
        "id": 70,
        "name": "The Executioner",
        "character_code": "K20",
        "role": "Killer",
        "gender": "Male",
        "origin": "Silent Hill",
        "realm": "Midwich Elementary School",
        "dlc": "Silent Hill Chapter",
        "year": 2020,
        "perk_1": "Forced Penance",
        "perk_2": "Trail of Torment",
        "perk_3": "Deathbound",
        "difficulty": "Hard",
        "power": "Rites of Judgement",
        "description": "A heavy control killer (Pyramid Head) who carves trenches into the floor to afflict survivors, bypassing standard hook mechanics entirely via Cages of Atonement.",
        "image": "https://deadbydaylight.com/static/1538c76190c8016b52dc33e1505b9677/32e6d/DBD_Killer_Executioner_only_5bb54b863d.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Jean-Baptiste Garnier (BHVR)"
    },
    {
        "id": 71,
        "name": "The Blight",
        "character_code": "K21",
        "role": "Killer",
        "gender": "Male",
        "origin": "Scotland",
        "realm": "Undisclosed",
        "dlc": "Descend Beyond Chapter",
        "year": 2020,
        "perk_1": "Dragon's Grip",
        "perk_2": "Hex: Blood Favor",
        "perk_3": "Hex: Undying",
        "difficulty": "Very Hard",
        "power": "Blighted Rush",
        "description": "A high-speed kinetic killer who drinks serum to bounce aggressively off environmental walls, launching lightning-fast lethal rush strikes down loops.",
        "image": "https://deadbydaylight.com/static/9ac591966078a53d892bdd96ddc61e80/64f54/DBD_Killer_Blight_only_2aee8a6af9.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Jean-Baptiste Garnier (BHVR) & Mathieu Favier (BHVR)"
    },
    {
        "id": 72,
        "name": "The Twins",
        "character_code": "K22",
        "role": "Killer",
        "gender": "Group",
        "origin": "France",
        "realm": "Undisclosed",
        "dlc": "A Binding of Kin Chapter",
        "year": 2020,
        "perk_1": "Hoarder",
        "perk_2": "Oppression",
        "perk_3": "Coupe de Grâce",
        "difficulty": "Very Hard",
        "power": "Blood Bond",
        "description": "A dual-character tag killer who splits her conjoined twin Victor from Charlotte's chest, controlling him to run at high speed and pounce on survivor backs.",
        "image": "https://deadbydaylight.com/static/649cc9013a47c71d43f688f439ec5173/be6cc/DBD_Killer_Twins_only_525459f74d.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Charlotte: Catherine Gauthier (BHVR); Victor: Jean-Baptiste Garnier (BHVR)"
    },
    {
        "id": 73,
        "name": "The Trickster",
        "character_code": "K23",
        "role": "Killer",
        "gender": "Male",
        "origin": "South Korea",
        "realm": "All-Kill Realm",
        "dlc": "All-Kill Chapter",
        "year": 2021,
        "perk_1": "Starstruck",
        "perk_2": "Hex: Crowd Control",
        "perk_3": "No Way Out",
        "difficulty": "Easy",
        "power": "Showstopper",
        "description": "A flamboyant ranged killer who unleashes rapid-fire volleys of throwing knives to fill up a survivor's laceration meter from medium range.",
        "image": "https://deadbydaylight.com/static/e18a0bd6ac96324b1d2602da1bcbab03/714c6/DBD_Killer_Trickster_only_d4def7ebe7.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Titus Kim (Voice Actor)"
    },
    {
        "id": 74,
        "name": "The Nemesis",
        "character_code": "K24",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Lethal Pursuer",
        "perk_2": "Hysteria",
        "perk_3": "Eruption",
        "difficulty": "Easy",
        "power": "T-Virus",
        "description": "An evolving juggernaut bio-weapon killer who whips survivors with an infection tentacle to increase his power reach, supported by roaming AI zombies.",
        "image": "https://deadbydaylight.com/static/40f14945a0bb25c8ade4b655067e2b7b/0d27d/DBD_Killer_Nemesis_only_1f21d6c597.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Sébastien Croteau (Nemesis); Roxana B.L. (Female Zombie); David A.B. (Male Zombie) (The Monster Factory)"
    },
    {
        "id": 75,
        "name": "The Cenobite",
        "character_code": "K25",
        "role": "Killer",
        "gender": "Male",
        "origin": "Labyrinth",
        "realm": "Base Game",
        "dlc": "Hellraiser Paragraph",
        "year": 2021,
        "perk_1": "Deadlock",
        "perk_2": "Hex: Plaything",
        "perk_3": "Scourge Hook: Gift of Pain",
        "difficulty": "Hard",
        "power": "Summons of Pain",
        "description": "A global harassment killer (Pinhead) who shoots guided gateway hooks to tie down survivors, forcing them to find a puzzle box to halt constant passive chain attacks.",
        "image": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/97/New_Store_Cenobite.png/revision/latest?cb=20220618153646",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Doug Bradley (Original Actor)"
    },
    {
        "id": 76,
        "name": "The Artist",
        "character_code": "K26",
        "role": "Killer",
        "gender": "Female",
        "origin": "Chile",
        "realm": "Eyrie of Crows",
        "dlc": "Portrait of a Murder Chapter",
        "year": 2021,
        "perk_1": "Grim Embrace",
        "perk_2": "Scourge Hook: Pain Resonance",
        "perk_3": "Hex: Pentimento",
        "difficulty": "Intermediate",
        "power": "Birds of Torment",
        "description": "A tactical long-distance cross-map killer who sets ink crows on walls, firing them directly through solid objects to swarm or injure survivors across the realm.",
        "image": "https://deadbydaylight.com/static/1375bac7853d2b422c9d402512b33c37/2d973/DBD_Killer_Artist_only_bbf9b6d6c0.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Beatrix Moersch"
    },
    {
        "id": 77,
        "name": "The Onryō",
        "character_code": "K27",
        "role": "Killer",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Base Game",
        "dlc": "Sadako Rising Chapter",
        "year": 2022,
        "perk_1": "Scourge Hook: Floods of Rage",
        "perk_2": "Call of Brine",
        "perk_3": "Merciless Storm",
        "difficulty": "Intermediate",
        "power": "Deluge of Fear",
        "description": "A creeping psychological curse killer (Sadako) who manifests out of active TV monitors to build up Condemned status layers on survivors, allowing instant executions.",
        "image": "https://deadbydaylight.com/static/2738fa84a2543b75bf57737f50eea39d/de856/DBD_Killer_Sadako_only_d334828435.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "None"
    },
    {
        "id": 78,
        "name": "The Dredge",
        "character_code": "K28",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "Undisclosed",
        "realm": "Garden of Joy",
        "dlc": "Roots of Dread Chapter",
        "year": 2022,
        "perk_1": "Dissolution",
        "perk_2": "Darkness Revealed",
        "perk_3": "Septic Touch",
        "difficulty": "Intermediate",
        "power": "Reign of Darkness",
        "description": "An amorphous manifestation of negative energy that teleports inside map lockers, materializes remnants during loops, and triggers a pitch-black Nightfall shroud.",
        "image": "https://deadbydaylight.com/static/57a2ab46664c85b21eb33df3805bf8c3/333f3/DBD_Killer_Dredge_only_c28a27b6df.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Roxana B.L.; Maude Théberge; Vanessa Landry; Misha Standjofski; Philippe Langelier; Sébastien Croteau (The Monster Factory)"
    },
    {
        "id": 79,
        "name": "The Mastermind",
        "character_code": "K29",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Superior Anatomy",
        "perk_2": "Awakened Awareness",
        "perk_3": "Terminus",
        "difficulty": "Intermediate",
        "power": "Virulent Bound",
        "description": "A high-speed bio-engineered predator (Albert Wesker) who dashes twice to grab and throw survivors, infecting them with a slowing Uroboros pathogen.",
        "image": "https://deadbydaylight.com/static/840fe6a15ff6ac71baea9db50c32e990/ef384/DBD_Killer_Albert_Uroboros_only_77cebee344.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Connor Fogarty (The Monster Factory)"
    },
    {
        "id": 80,
        "name": "The Knight",
        "character_code": "K30",
        "role": "Killer",
        "gender": "Male",
        "origin": "Italy",
        "realm": "The Shattered Square",
        "dlc": "Forged in Fog Chapter",
        "year": 2022,
        "perk_1": "Nowhere to Hide",
        "perk_2": "Hex: Face the Darkness",
        "perk_3": "Hubris",
        "difficulty": "Intermediate",
        "power": "Guardia Compagnia",
        "description": "A tactical squad commander killer who draws physical search paths to summon AI spectral guards, tasking them to destroy objects or hunt survivors down.",
        "image": "https://deadbydaylight.com/static/31c5ecfd7979d01016dafb3031176deb/cac3b/DBD_Killer_The_Knight_only_ddaf0f74ff.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Misha Standjofski (Knight); David A.B. (Carnifex); Simon Girard (Assassin); Jeff Mott (Jailer) (The Monster Factory)"
    },
    {
        "id": 81,
        "name": "The Skull Merchant",
        "character_code": "K31",
        "role": "Killer",
        "gender": "Female",
        "origin": "Brazil",
        "realm": "Shelter Woods",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "Thwack!",
        "perk_2": "Leverage",
        "perk_3": "Game Afoot",
        "difficulty": "Easy",
        "power": "Eyes in the Sky",
        "description": "A high-tech hunting tracker who deploys spinning surveillance drones to map out territories, exposing survivors and tracking their exact positions.",
        "image": "https://deadbydaylight.com/static/c364f528d9ee002b283a453ef0963649/06b08/DBD_Killer_The_Skull_Merchant_only_cbca2c0957.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Viky Boyer (The Monster Factory)"
    },
    {
        "id": 82,
        "name": "The Singularity",
        "character_code": "K32",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "Toba Landing",
        "realm": "Toba Landing",
        "dlc": "End Transmission Chapter",
        "year": 2023,
        "perk_1": "Genetic Limits",
        "perk_2": "Forced Hesitation",
        "perk_3": "Machine Learning",
        "difficulty": "Very Hard",
        "power": "Quantum Instantiation",
        "description": "A corrupted AI lifeform that shoots biopod cameras onto structural surfaces, shooting slipstream nodes onto survivors to teleport straight behind them.",
        "image": "https://deadbydaylight.com/static/ca427decdaf86c120784d8eb10be2bc6/173e8/CM_1432_DBD_Website_Ch28_Character_Page_Killer_Singularity_ONLY_199b669864.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Unknown"
    },
    {
        "id": 83,
        "name": "The Xenomorph",
        "character_code": "K33",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "Nostromo Wreckage",
        "realm": "Nostromo Wreckage",
        "dlc": "Alien Chapter",
        "year": 2023,
        "perk_1": "Rapid Brutality",
        "perk_2": "Alien Instinct",
        "perk_3": "Ultimate Weapon",
        "difficulty": "Easy",
        "power": "Hidden Pursuit",
        "description": "An iconic alien predator that crawls on all fours through sub-surface floor tunnels, emerging at control stations to strike loops using a razor-sharp tail lash.",
        "image": "https://deadbydaylight.com/static/f2a90cd827af5aa5e36279ab007253ce/9f503/CM_1549_DBD_Character_Render_Killer_Xenomorph_45dfe1e09a.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Sébastien Croteau (The Monster Factory)"
    },
    {
        "id": 84,
        "name": "The Good Guy",
        "character_code": "K34",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Chucky Chapter",
        "year": 2023,
        "perk_1": "Hex: Two Can Play",
        "perk_2": "Friends 'Til the End",
        "perk_3": "Batteries Included",
        "difficulty": "Hard",
        "power": "Playtime's Over",
        "description": "A diminutive, third-person perspective killer doll (Chucky) who completely hides his physical form in white footprints, launching scamper slice rushes under loops.",
        "image": "https://deadbydaylight.com/static/42fe9477c529d4e03acde37b0d1c1e21/dfece/CM_1660_DBD_Character_Renders_Killer_23c9551fea.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Brad Dourif (Original Actor)"
    },
    {
        "id": 85,
        "name": "The Unknown",
        "character_code": "K35",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "United States",
        "realm": "Forgotten Ruins",
        "dlc": "All Things Wicked Chapter",
        "year": 2024,
        "perk_1": "Unbound",
        "perk_2": "Unforeseen",
        "perk_3": "Undone",
        "difficulty": "Hard",
        "power": "UVX",
        "description": "A bizarre cryptid horror that bounces structural venom toxins off loop walls to weaken survivors, dropping stationary decoys to instantly teleport across tiles.",
        "image": "https://deadbydaylight.com/static/4d498c3ffb28512cb44bc36164259541/4d32b/DBD_Website_Ch31_Character_Page_Killer_The_Unknown_e603fc0678.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Zoey Alexandria (Professional Transvoice Teacher)"
    },
    {
        "id": 86,
        "name": "The Lich",
        "character_code": "K36",
        "role": "Killer",
        "gender": "Male",
        "origin": "Oerth",
        "realm": "Forgotten Ruins",
        "dlc": "Dungeons & Dragons Chapter",
        "year": 2024,
        "perk_1": "Languid Bleed",
        "perk_2": "Weave Attunement",
        "perk_3": "Dark Arrogance",
        "difficulty": "Hard",
        "power": "Vile Book of Spells",
        "description": "An ancient sorcerer (Vecna) who toggles through four magical spell types to lift dropped pallets, fly over gaps, track items, or launch magical skeletons.",
        "image": "https://deadbydaylight.com/static/c69220d5d81bdf443501bfb07418035e/d17e6/DBD_Website_Ch32_Character_Page_Killer_Vecna_ONLY_7e9136c8c7.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Matt Mercer (Voice Actor and Game Designer)"
    },
    {
        "id": 87,
        "name": "The Dark Lord",
        "character_code": "K37",
        "role": "Killer",
        "gender": "Male",
        "origin": "Wallachia",
        "realm": "Castle Dracula",
        "dlc": "Castlevania Chapter",
        "year": 2024,
        "perk_1": "Hex: Wretched Fate",
        "perk_2": "Human Greed",
        "perk_3": "Dominance",
        "difficulty": "Hard",
        "power": "Transformation",
        "description": "A shape-shifting vampire king (Dracula) who transitions between Vampire form to cast hellfire columns, Wolf form to chase scent tracks, and Bat form to teleport over vaults.",
        "image": "https://deadbydaylight.com/static/f1a04bf8578d04e99f80941bb5703836/40a45/DBD_ECLAIR_WEBPAGE_Character_Page_Killer_DRACULA_ONLY_0e06f099cb.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Crispin Freeman (Voice Actor)"
    },
    {
        "id": 88,
        "name": "The Houndmaster",
        "character_code": "K38",
        "role": "Killer",
        "gender": "Female",
        "origin": "United States",
        "realm": "The Void",
        "dlc": "Doomed Course Chapter",
        "year": 2024,
        "perk_1": "All-shaking Thunder",
        "perk_2": "Scourged Hook: Jagged Compass",
        "perk_3": "No Quarter",
        "difficulty": "Intermediate",
        "power": "Scent of Blood",
        "description": "Cast adrift by a horrific tragedy, Portia Maye arose from the blood with renewed purpose: to inflict unspeakable pain on those who tore her family apart. With her loyal dog forever at her side, her insatiable lust for violence runs deeper than the darkest ocean trench.",
        "image": "https://deadbydaylight.com/static/e4616484af0706362e35f613c864973d/504aa/DBD_GELATO_WEBPAGE_Character_Page_KILLER_ONLY_9b9cd1c91f.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Debra Wilson (Blindlight)"
    },
    {
        "id": 89,
        "name": "The Ghoul",
        "character_code": "K39",
        "role": "Killer",
        "gender": "Male",
        "origin": "Japan",
        "realm": "None",
        "dlc": "Chapter 35: Tokyo Ghoul",
        "year": 2025,
        "perk_1": "Hex: Nothing But Misery",
        "perk_2": "Forever Entwined",
        "perk_3": "None Are Free",
        "difficulty": "Intermediate",
        "power": "One-Eyed Terror",
        "description": "An aggressive, half-ghoul killer who thrives on slowing survivors in chases, speeding up hook pickups, and locking down windows and standing pallets during the endgame.",
        "image": "https://deadbydaylight.com/static/9df1bc372b5ac7892b0b61d114720944/b6bfd/DBD_GELATO_WEBPAGE_Character_Page_KILLER_CHARACTER_ONLY_425ce91cd7.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Natsuki Hanae (Original Voice Actor)"
    },
    {
        "id": 90,
        "name": "The Krasue",
        "character_code": "K41",
        "role": "Killer",
        "gender": "Female",
        "origin": "Thailand",
        "realm": "None",
        "dlc": "Chapter 37: Sinister Grace",
        "year": 2025,
        "perk_1": "Ravenous",
        "perk_2": "Wandering Eye",
        "perk_3": "Hex: Overture of Doom",
        "difficulty": "Hard",
        "power": "Visceral Flight",
        "description": "A split-form killer inspired by Thai folklore who detaches her floating head to lunge out with a long-range Intestinal Whip, while her perks maximize map-wide tracking, false terror radii, and sudden endgame pressure.",
        "image": "https://deadbydaylight.com/static/66c166b08c4b63eb1c25c4078ac58566/82cf4/DBD_MAPLE_CH_WEB_CHARACTERPAGE_KILLER_Krasue_01_2a1bf40066.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Body Form: Organ Prawang (Opera Singer); Head Form: Roxana B.L. (The Monster Factory)"
    },
    {
        "id": 91,
        "name": "The Slasher",
        "character_code": "K35_JV",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "None",
        "dlc": "Chapter 40: Jason",
        "year": 2026,
        "perk_1": "Hex: Scared to Death",
        "perk_2": "Silent Shadow",
        "perk_3": "Rampage",
        "difficulty": "Easy",
        "power": "Omnipresent Evil",
        "description": "A relentless, masked powerhouse (Jason Voorhees) who blends high-speed invisible map teleportation with a brutal projectile-flinging mechanics to isolate and pin down survivors.",
        "image": "https://deadbydaylight.com/static/b88b3476b9c2ad477d484ba2078468b7/ca5bd/DBD_SUSHI_CHAPTER_Character_Page_Jason_CHARACTER_77eb1fa23f.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "None"
    },
    {
        "id": 92,
        "name": "The Judgment",
        "character_code": "K42",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "Terra Primus",
        "realm": "None",
        "dlc": "Chapter 38: Chorus of Sin",
        "year": 2026,
        "perk_1": "Celestial Witness",
        "perk_2": "Hex: Under Your Thumb",
        "perk_3": "Lay Waste",
        "difficulty": "Very Hard",
        "power": "Divine Condemned",
        "description": "A punishing celestial entity that casts down columns of divine light to brand survivors with Heresy, allowing it to banish downed heretics straight into the grueling trial of Exile.",
        "image": "https://deadbydaylight.com/static/31dfb99c3863c874547592463c4785b7/ca5bd/DBD_UDON_CHAPTER_STAND_ALONE_RENDERS_WEB_ASSETS_THE_JUDGMENT_CHARACTER_ONLY_af1b049c5a.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Elsie Lovelock (Voice Actress)"
    },
    {
        "id": 93,
        "name": "The First (Henry Creel / Vecna)",
        "character_code": "K45",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Hawkins National Laboratory",
        "dlc": "Chapter 39: Stranger Things 2",
        "year": 2026,
        "perk_1": "Turn Back The Clock",
        "perk_2": "Secret Project",
        "perk_3": "Hex: Hive Mind",
        "difficulty": "Hard",
        "power": "Test Subject #001",
        "description": "A telekinetic horror born from Henry Creel's descent into the Upside Down, who tears open dimensional Vine gates to traverse the map and unleashes a devastating Undergate strike to snap survivors' minds and bodies alike.",
        "image": "https://deadbydaylight.com/static/46fd87ede14695260195ddbc2691f431/5bd17/DBD_POUTINE_WEBPAGE_Character_Page_THEFIRST_ONLY_58ed00b1f5.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "Andrew Morgado (Voice Actor)"
    },
    {
        "id": 94,
        "name": "The Animatronic (William Afton / Springtrap)",
        "character_code": "K40",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Withered Isle",
        "dlc": "Chapter 36: Five Nights at Freddy's",
        "year": 2025,
        "perk_1": "Help Wanted",
        "perk_2": "Phantom Fear",
        "perk_3": "Haywire",
        "difficulty": "Hard",
        "power": "Fazbear's Fright",
        "description": "The Five Nights at Freddy's antagonist trapped inside a decaying Spring Bonnie suit, who throws an embedded fire axe at fleeing survivors and spawns lockable Security Doors across the map to trap them inside sealed rooms.",
        "image": "https://deadbydaylight.com/static/5834e921a7ce2c9eb75c618bedc7131f/494af/DBD_KETCHUP_WEBPAGE_Asset_CHARACTER_ONLY_SPRINGTRAP_99e8fac4d1.webp",
        "movement_speed": "4.0",
        "terror_radius": "32",
        "height": "N/A",
        "voice_actor": "PJ Heywood (Original Voice Actor)"
    }
]

# Validate all character dictionaries
characters = [Character(**character).model_dump() for character in characters]

# ============================================================
# API KEY AUTHENTICATION
# ============================================================
def verify_api_key(x_api_key: Optional[str] = Header(default=None)):
    if x_api_key != API_KEY:
        raise HTTPException(
            status_code=401,
            detail="Invalid or missing API key."
        )
    return True

# ============================================================
# HEALTH CHECK (Public)
# ============================================================
@app.get("/health")
def health_check():
    return {
        "status": "ok",
        "service": "Dead by Daylight Character Directory API",
        "version": API_VERSION,
        "timestamp": datetime.now(timezone.utc).isoformat()
    }

# ============================================================
# ROOT
# ============================================================
@app.get("/api/v1/")
def home():
    return {
        "message": "Welcome to the Dead by Daylight Character Directory API!",
        "version": API_VERSION,
        "total_characters": len(characters),
        "survivors_count": len([c for c in characters if c["role"] == "Survivor"]),
        "killers_count": len([c for c in characters if c["role"] == "Killer"]),
        "endpoints": [
            "/api/v1/characters",
            "/api/v1/characters/search",
            "/api/v1/characters/{character_id}"
        ]
    }

# ============================================================
# GET ALL CHARACTERS (Protected)
# ============================================================
@app.get("/api/v1/characters", dependencies=[Depends(verify_api_key)])
def get_characters(
    role: str = Query(None, description="Filter by 'Survivor' or 'Killer'"),
    sort_by: str = Query("name", description="Sort field: 'name', 'year', 'difficulty', 'character_code'"),
    order: str = Query("asc", description="'asc' or 'desc'"),
    limit: int = Query(10, ge=1, le=100, description="Items per page"),
    offset: int = Query(0, ge=0, description="Page starting offset")
):
    results = characters

    if role:
        results = [c for c in results if c["role"].lower() == role.lower()]
    reverse = order.lower() == "desc"
    if sort_by in ["name", "year", "difficulty", "character_code"]:
        results = sorted(
            results,
            key=lambda x: str(x.get(sort_by, "")).lower(),
            reverse=reverse
        )

    total_count = len(results)
    paginated_results = results[offset: offset + limit]

    return {
        "total": total_count,
        "limit": limit,
        "offset": offset,
        "characters": paginated_results
    }


# ============================================================
# SEARCH CHARACTERS (Protected)
# ============================================================
@app.get("/api/v1/characters/search", dependencies=[Depends(verify_api_key)])
def search_characters(
    q: str = Query(..., min_length=1),
    limit: int = Query(10, ge=1, le=100),
    offset: int = Query(0, ge=0)
):
    search_query = q.lower()
    results = []

    for character in characters:
        searchable_text = (
            f"{character['id']} "
            f"{character['name']} "
            f"{character['character_code']} "
            f"{character['role']} "
            f"{character['gender']} "
            f"{character['origin']} "
            f"{character['realm']} "
            f"{character['dlc']} "
            f"{character['year']} "
            f"{character['perk_1']} "
            f"{character['perk_2']} "
            f"{character['perk_3']} "
            f"{character['difficulty']} "
            f"{character.get('power', '')} "
            f"{character['description']} "
            f"{character['movement_speed']} "
            f"{character['terror_radius']} "
            f"{character.get('height', '')} "
            f"{character['voice_actor']}"
        ).lower()

        if search_query in searchable_text:
            results.append(character)

    total_count = len(results)
    paginated_results = results[offset: offset + limit]
    return {
        "query": q,
        "total": total_count,
        "limit": limit,
        "offset": offset,
        "results": paginated_results
    }

# ============================================================
# GET ONE CHARACTER (Protected)
# ============================================================
@app.get("/api/v1/characters/{character_id}", dependencies=[Depends(verify_api_key)])
def get_character(character_id: int):
    for character in characters:
        if character["id"] == character_id:
            return character
    raise HTTPException(
        status_code=404,
        detail="Character not found."
    )
