from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="Dead by Daylight Character Directory API",
    description="A REST API containing all 54 Survivors and 44 Killers in Dead by Daylight with 14 unique fields each.",
    version="2.0.0",
    root_path="/api"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

characters = [
    # =========================================================================
    # SURVIVORS (54 TOTAL)
    # =========================================================================
    {
        "id": 1,
        "name": "Dwight Fairfield",
        "character_code": "S01",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Crotus Prenn Asylum",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Bond",
        "perk_2": "Prove Thyself",
        "perk_3": "Leader",
        "difficulty": "Easy",
        "description": "A nervous leader whose perks help allies locate one another and increase team repair and action efficiency."
    },
    {
        "id": 2,
        "name": "Meg Thomas",
        "character_code": "S02",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "MacMillan Estate",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Quick & Quiet",
        "perk_2": "Sprint Burst",
        "perk_3": "Adrenaline",
        "difficulty": "Easy",
        "description": "An energetic athlete capable of outrunning danger, vaulting silently, and escaping high-pressure chases."
    },
    {
        "id": 3,
        "name": "Claudette Morel",
        "character_code": "S03",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Canada",
        "realm": "Autohaven Wreckers",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Empathy",
        "perk_2": "Botany Knowledge",
        "perk_3": "Self-Care",
        "difficulty": "Easy",
        "description": "A studious botanist who uses her knowledge to heal herself and her teammates with high efficiency."
    },
    {
        "id": 4,
        "name": "Jake Park",
        "character_code": "S04",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Red Forest",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Iron Will",
        "perk_2": "Calm Spirit",
        "perk_3": "Saboteur",
        "difficulty": "Easy",
        "description": "A solitary survivalist capable of sabotaging meat hooks quietly and staying calm under intense pressure."
    },
    {
        "id": 5,
        "name": "Nea Karlsson",
        "character_code": "S05",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Sweden",
        "realm": "Crotus Prenn Asylum",
        "dlc": "The Last Breath Chapter",
        "year": 2016,
        "perk_1": "Balanced Landing",
        "perk_2": "Urban Evasion",
        "perk_3": "Streetwise",
        "difficulty": "Intermediate",
        "description": "An urban artist skilled in stealth, crouch-walking quickly, and landing safely from extreme heights."
    },
    {
        "id": 6,
        "name": "Laurie Strode",
        "character_code": "S06",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Haddonfield",
        "dlc": "The Halloween Chapter",
        "year": 2016,
        "perk_1": "Sole Survivor",
        "perk_2": "Object of Obsession",
        "perk_3": "Decisive Strike",
        "difficulty": "Hard",
        "description": "A resilient survivor whose determination allows her to become the Killer's Obsession and break free from grasps."
    },
    {
        "id": 7,
        "name": "Ace Visconti",
        "character_code": "S07",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Argentina",
        "realm": "Backwater Swamp",
        "dlc": "Of Flesh and Mud Chapter",
        "year": 2016,
        "perk_1": "Open-Handed",
        "perk_2": "Up the Ante",
        "perk_3": "Ace in the Hole",
        "difficulty": "Easy",
        "description": "A lucky gambler who boosts aura reading ranges and increases luck and chest add-on quality for the team."
    },
    {
        "id": 8,
        "name": "William 'Bill' Overbeck",
        "character_code": "S08",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Left Behind Paragraph",
        "year": 2017,
        "perk_1": "Left Behind",
        "perk_2": "Borrowed Time",
        "perk_3": "Unbreakable",
        "difficulty": "Hard",
        "description": "A tough military veteran accustomed to sacrificing himself for the group and picking himself up from dying states."
    },
    {
        "id": 9,
        "name": "Feng Min",
        "character_code": "S09",
        "role": "Survivor",
        "gender": "Female",
        "origin": "China",
        "realm": "Léry's Memorial Institute",
        "dlc": "Spark of Madness Chapter",
        "year": 2017,
        "perk_1": "Technician",
        "perk_2": "Lithe",
        "perk_3": "Alert",
        "difficulty": "Easy",
        "description": "An esports competitor who repairs generators quietly, gains speed when vaulting, and tracks Killer actions."
    },
    {
        "id": 10,
        "name": "David King",
        "character_code": "S10",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United Kingdom",
        "realm": "Red Forest",
        "dlc": "A Lullaby for the Dark Chapter",
        "year": 2017,
        "perk_1": "We're Gonna Live Forever",
        "perk_2": "Dead Hard",
        "perk_3": "No Mither",
        "difficulty": "Hard",
        "description": "A rugged brawler who takes hits for his teammates, pushes through injuries, and withstands fatal blows."
    },
    {
        "id": 11,
        "name": "Quentin Smith",
        "character_code": "S11",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Springwood",
        "dlc": "A Nightmare on Elm Street Chapter",
        "year": 2017,
        "perk_1": "Wake Up!",
        "perk_2": "Pharmacy",
        "perk_3": "Vigil",
        "difficulty": "Intermediate",
        "description": "A sleepy survivor who opens exit gates faster, loots med-kits reliably, and reduces status effect durations."
    },
    {
        "id": 12,
        "name": "Detective David Tapp",
        "character_code": "S12",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Gideon Meat Plant",
        "dlc": "The SAW Chapter",
        "year": 2018,
        "perk_1": "Tenacity",
        "perk_2": "Detective's Intuition",
        "perk_3": "Stake Out",
        "difficulty": "Intermediate",
        "description": "An obsessed detective who crawls quickly while recovering and tracks objective auras after generator completions."
    },
    {
        "id": 13,
        "name": "Kate Denson",
        "character_code": "S13",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Campbell's Chapel",
        "dlc": "Curtain Call Chapter",
        "year": 2018,
        "perk_1": "Dance With Me",
        "perk_2": "Windows of Opportunity",
        "perk_3": "Boil Over",
        "difficulty": "Easy",
        "description": "A hopeful songbird who tracks vault and pallet auras and fiercely resists being carried to hooks."
    },
    {
        "id": 14,
        "name": "Adam Francis",
        "character_code": "S14",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Jamaica",
        "realm": "Yamaoka Estate",
        "dlc": "Shattered Bloodline Chapter",
        "year": 2018,
        "perk_1": "Diversion",
        "perk_2": "Deliverance",
        "perk_3": "Autodidact",
        "difficulty": "Hard",
        "description": "A resourceful teacher capable of distracting Killers with pebbles and unhooking himself securely."
    },
    {
        "id": 15,
        "name": "Jeff Johansen",
        "character_code": "S15",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Canada",
        "realm": "Ormond",
        "dlc": "Darkness Among Us Chapter",
        "year": 2018,
        "perk_1": "Breakdown",
        "perk_2": "Aftercare",
        "perk_3": "Distortion",
        "difficulty": "Easy",
        "description": "A quiet artist whose perks break hooks upon escape, show team auras, and hide his own from the Killer."
    },
    {
        "id": 16,
        "name": "Jane Romero",
        "character_code": "S16",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "The Plague's Temple",
        "dlc": "Demise of the Faithful Chapter",
        "year": 2019,
        "perk_1": "Solidarity",
        "perk_2": "Poised",
        "perk_3": "Head On",
        "difficulty": "Intermediate",
        "description": "An influential talk show host who heals while healing others, hides scratch marks on generator completions, and stuns Killers out of lockers."
    },
    {
        "id": 17,
        "name": "Ash Williams",
        "character_code": "S17",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Ash vs Evil Dead Paragraph",
        "year": 2019,
        "perk_1": "Flip-Flop",
        "perk_2": "Buckle Up",
        "perk_3": "Mettle of Man",
        "difficulty": "Hard",
        "description": "A legendary demon hunter who converts recovery progress to wiggle progress and absorbs fatal blows."
    },
    {
        "id": 18,
        "name": "Nancy Wheeler",
        "character_code": "S18",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Inner Strength",
        "perk_2": "Fixated",
        "perk_3": "Better Together",
        "difficulty": "Easy",
        "description": "A headstrong journalist who heals herself by cleansing totems, sees her own scratch marks, and highlights generators for nearby allies."
    },
    {
        "id": 19,
        "name": "Steve Harrington",
        "character_code": "S19",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Babysitter",
        "perk_2": "Camaraderie",
        "perk_3": "Second Wind",
        "difficulty": "Intermediate",
        "description": "A protective former popular kid who pauses hook struggle timers and hides unhooked teammates' pools of blood and scratch marks."
    },
    {
        "id": 20,
        "name": "Yui Kimura",
        "character_code": "S20",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Cursed Legacy Chapter",
        "year": 2019,
        "perk_1": "Lucky Break",
        "perk_2": "Any Means Necessary",
        "perk_3": "Breakout",
        "difficulty": "Easy",
        "description": "A hardened street racer who resets dropped pallets, hides her pools of blood when injured, and aids wiggling allies."
    },
    {
        "id": 21,
        "name": "Zarina Kassir",
        "character_code": "S21",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Lebanon",
        "realm": "Grave of Glenvale",
        "dlc": "Chains of Hate Chapter",
        "year": 2020,
        "perk_1": "Off the Record",
        "perk_2": "Red Herring",
        "perk_3": "For the People",
        "difficulty": "Hard",
        "description": "An independent filmmaker capable of instantly healing others at her own expense and masking her aura after being unhooked."
    },
    {
        "id": 22,
        "name": "Cheryl Mason",
        "character_code": "S22",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Midwich Elementary School",
        "dlc": "Silent Hill Chapter",
        "year": 2020,
        "perk_1": "Soul Guard",
        "perk_2": "Blood Pact",
        "perk_3": "Repressed Alliance",
        "difficulty": "Hard",
        "description": "A resilient young woman who blocks generators from the Killer's regression using the Entity and gains endurance after healing."
    },
    {
        "id": 23,
        "name": "Felix Richter",
        "character_code": "S23",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Germany",
        "realm": "Undisclosed",
        "dlc": "Descend Beyond Chapter",
        "year": 2020,
        "perk_1": "Visionary",
        "perk_2": "Desperate Measures",
        "perk_3": "Built to Last",
        "difficulty": "Easy",
        "description": "A brilliant architect who refills depleted item charges inside lockers and gains speed boosts to actions based on injured allies."
    },
    {
        "id": 24,
        "name": "Élodie Rakoto",
        "character_code": "S24",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Madagascar",
        "realm": "Undisclosed",
        "dlc": "A Binding of Kin Chapter",
        "year": 2020,
        "perk_1": "Appraisal",
        "perk_2": "Deception",
        "perk_3": "Power Struggle",
        "difficulty": "Hard",
        "description": "An occult investigator who rummages through opened chests, fakes locker entries, and drops pallets on the Killer while being carried."
    },
    {
        "id": 25,
        "name": "Yun-Jin Lee",
        "character_code": "S25",
        "role": "Survivor",
        "gender": "Female",
        "origin": "South Korea",
        "realm": "All-Kill Realm",
        "dlc": "All-Kill Chapter",
        "year": 2021,
        "perk_1": "Fast Track",
        "perk_2": "Smash Hit",
        "perk_3": "Self-Preservation",
        "difficulty": "Easy",
        "description": "A self-serving music producer who benefits from her teammates' misfortunes, gaining generator tokens and sprint bursts from pallet stuns."
    },
    {
        "id": 26,
        "name": "Jill Valentine",
        "character_code": "S26",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Counterforce",
        "perk_2": "Resurgence",
        "perk_3": "Blast Mine",
        "difficulty": "Easy",
        "description": "An elite police operative who cleanses totems rapidly, regains instant healing progress upon unhooking, and traps generators with blinding mines."
    },
    {
        "id": 27,
        "name": "Leon S. Kennedy",
        "character_code": "S27",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Bite the Bullet",
        "perk_2": "Flashbang",
        "perk_3": "Rookie Spirit",
        "difficulty": "Easy",
        "description": "An idealistic rookie cop who completely silences his healing sounds and crafts blinding flashbang grenades inside lockers."
    },
    {
        "id": 28,
        "name": "Mikaela Reid",
        "character_code": "S28",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Hour of the Witch Chapter",
        "year": 2021,
        "perk_1": "Clairvoyance",
        "perk_2": "Boon: Circle of Healing",
        "perk_3": "Boon: Shadow Step",
        "difficulty": "Intermediate",
        "description": "A modern witch who blesses totems to create areas where survivors can heal quickly and hide their scratch marks."
    },
    {
        "id": 29,
        "name": "Jonah Vasquez",
        "character_code": "S29",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Eyrie of Crows",
        "dlc": "Portrait of a Murder Chapter",
        "year": 2021,
        "perk_1": "Overcome",
        "perk_2": "Corrective Action",
        "perk_3": "Boon: Exponential",
        "difficulty": "Easy",
        "description": "A brilliant codebreaker who extends hit speed bursts and creates a recovery oasis for downed allies using Boon totems."
    },
    {
        "id": 30,
        "name": "Yoichi Asakawa",
        "character_code": "S30",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Japan",
        "realm": "Base Game",
        "dlc": "Sadako Rising Chapter",
        "year": 2022,
        "perk_1": "Parental Guidance",
        "perk_2": "Empathic Connection",
        "perk_3": "Boon: Dark Theory",
        "difficulty": "Intermediate",
        "description": "A psychic marine biologist who completely hides blood, scratches, and grunts after stunning a killer, and blesses totems to grant speed boosts."
    },
    {
        "id": 31,
        "name": "Haddie Kaur",
        "character_code": "S31",
        "role": "Survivor",
        "gender": "Female",
        "origin": "India",
        "realm": "Garden of Joy",
        "dlc": "Roots of Dread Chapter",
        "year": 2022,
        "perk_1": "Inner Focus",
        "perk_2": "Residual Manifest",
        "perk_3": "Overzealous",
        "difficulty": "Easy",
        "description": "A psychic podcaster who sees nearby ally scratch marks, blinds Killers to inflict blindness, and increases repair speed after cleansing totems."
    },
    {
        "id": 32,
        "name": "Ada Wong",
        "character_code": "S32",
        "role": "Survivor",
        "gender": "Female",
        "origin": "China",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Wiretap",
        "perk_2": "Reactive Healing",
        "perk_3": "Low Profile",
        "difficulty": "Easy",
        "description": "A secretive spy who installs camera wiretaps on generators, heals instantly when nearby allies are hit, and hides traces when the lone survivor."
    },
    {
        "id": 33,
        "name": "Rebecca Chambers",
        "character_code": "S33",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Better Than New",
        "perk_2": "Hyperfocus",
        "perk_3": "Reassurance",
        "difficulty": "Hard",
        "description": "A young prodigy medic who pauses the sacrifice timer of hooked allies and rewards rapid consecutive Great Skill Checks with huge repair bursts."
    },
    {
        "id": 34,
        "name": "Vittorio Toscano",
        "character_code": "S34",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Italy",
        "realm": "The Shattered Square",
        "dlc": "Forged in Fog Chapter",
        "year": 2022,
        "perk_1": "Potential Energy",
        "perk_2": "Fogwise",
        "perk_3": "Quick Gambit",
        "difficulty": "Intermediate",
        "description": "An ancient, arcane scholar who stores generator progression to instantly dump it elsewhere and reveals the Killer during Great Skill Checks."
    },
    {
        "id": 35,
        "name": "Thalita Lyra",
        "character_code": "S35",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Brazil",
        "realm": "Shelter Woods",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "Cut Loose",
        "perk_2": "Friendly Competition",
        "perk_3": "Teamwork: Power of Two",
        "difficulty": "Easy",
        "description": "A community-focused kite fighter whose perks reward group generator repairs and synchronized vault maneuvers during chases."
    },
    {
        "id": 36,
        "name": "Renato Lyra",
        "character_code": "S36",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Brazil",
        "realm": "Shelter Woods",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "Blood Rush",
        "perk_2": "Background Player",
        "perk_3": "Teamwork: Collective Stealth",
        "difficulty": "Hard",
        "description": "A calm analyst who activates massive sprint bursts when the killer picks up an ally and can force exhaustion recovery at the cost of health."
    },
    {
        "id": 37,
        "name": "Gabriel Soma",
        "character_code": "S37",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Undisclosed",
        "realm": "Toba Landing",
        "dlc": "End Transmission Chapter",
        "year": 2023,
        "perk_1": "Troubleshooter",
        "perk_2": "Made for This",
        "perk_3": "Scavenger",
        "difficulty": "Intermediate",
        "description": "A cloned starship technician who runs faster when injured, reveals the highest-progress generator during chases, and recycles depleted toolboxes."
    },
    {
        "id": 38,
        "name": "Nicolas Cage",
        "character_code": "S38",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Nicolas Cage Paragraph",
        "year": 2023,
        "perk_1": "Dramaturgy",
        "perk_2": "Scene Partner",
        "perk_3": "Plot Twist",
        "difficulty": "Hard",
        "description": "An eccentric movie superstar who can scream to read killer auras, fake his own death to completely heal from the dying state, and gain random items."
    },
    {
        "id": 39,
        "name": "Ellen Ripley",
        "character_code": "S39",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Nostromo Wreckage",
        "dlc": "Alien Chapter",
        "year": 2023,
        "perk_1": "Lucky Star",
        "perk_2": "Chemical Trap",
        "perk_3": "Light-Footed",
        "difficulty": "Easy",
        "description": "An iron-willed space survivor who suppresses her footsteps while healthy and installs slowing chemical traps onto dropped pallets."
    },
    {
        "id": 40,
        "name": "Alan Wake",
        "character_code": "S40",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Alan Wake Chapter",
        "year": 2024,
        "perk_1": "Champion of Light",
        "perk_2": "Boon: Illumination",
        "perk_3": "Deadline",
        "difficulty": "Intermediate",
        "description": "A tormented writer who runs faster while shining flashlights, inflicts slowed movement on blinded killers, and alters skill check frequencies."
    },
    {
        "id": 41,
        "name": "Sable Ward",
        "character_code": "S41",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Forgotten Ruins",
        "dlc": "All Things Wicked Chapter",
        "year": 2024,
        "perk_1": "Invocation: Weaving Spiders",
        "perk_2": "Strength in Shadows",
        "perk_3": "Wicked",
        "difficulty": "Hard",
        "description": "A gothic alternative girl who performs dark invocations inside the basement to trade her health for permanent match-wide generator repair progress."
    },
    {
        "id": 42,
        "name": "Aestri Yazar",
        "character_code": "S42",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Faerûn",
        "realm": "Forgotten Ruins",
        "dlc": "Dungeons & Dragons Chapter",
        "year": 2024,
        "perk_1": "Mirrored Illusion",
        "perk_2": "Bardic Inspiration",
        "perk_3": "Still Sight",
        "difficulty": "Intermediate",
        "description": "An elven bard who casts illusory copies of herself on objectives and plays dice roll musical melodies to boost team performance."
    },
    {
        "id": 43,
        "name": "Lara Croft",
        "character_code": "S43",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United Kingdom",
        "realm": "Base Game",
        "dlc": "Tomb Raider Chapter",
        "year": 2024,
        "perk_1": "Finesse",
        "perk_2": "Hardened",
        "perk_3": "Specialist",
        "difficulty": "Easy",
        "description": "A legendary archaeologist who executes high-speed window vaults while healthy, bypasses screams, and permanently drops max generator requirements."
    },
    {
        "id": 44,
        "name": "Trevor Belmont",
        "character_code": "S44",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Wallachia",
        "realm": "Castle Dracula",
        "dlc": "Castlevania Chapter",
        "year": 2024,
        "perk_1": "Eyes of Belmont",
        "perk_2": "Exultation",
        "perk_3": "Moment of Glory",
        "difficulty": "Easy",
        "description": "A battle-hardened monster hunter who extends killer aura reveal durations and upgrades his current item tier upon stunning the killer."
    },
    {
        "id": 45,
        "name": "Sujata",
        "character_code": "S45",
        "role": "Survivor",
        "gender": "Female",
        "origin": "India",
        "realm": "The Void",
        "dlc": "Doomed Echoes Chapter",
        "year": 2024,
        "perk_1": "Flashover",
        "perk_2": "Boon: Dark Sanctum",
        "perk_3": "Hard Bargain",
        "difficulty": "Intermediate",
        "description": "A resourceful engineer capable of creating fake audio distractions on incomplete generators and protecting broken totems."
    },
    {
        "id": 46,
        "name": "Klaus Müller",
        "character_code": "S46",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Germany",
        "realm": "The Void",
        "dlc": "Doomed Echoes Chapter",
        "year": 2024,
        "perk_1": "Iron Sight",
        "perk_2": "Break the Ice",
        "perk_3": "Heavy Footing",
        "difficulty": "Easy",
        "description": "A heavy-set industrial worker whose perks allow him to instantly break out of traps and trade stealth for fast unhooking speed."
    },
    {
        "id": 47,
        "name": "Rick Grimes",
        "character_code": "S47",
        "role": "Survivor",
        "gender": "Male",
        "origin": "United States",
        "realm": "None",
        "dlc": "Chapter 34.5: The Walking Dead",
        "year": 2025,
        "perk_1": "Apocalyptic Ingenuity",
        "perk_2": "Come and Get Me!",
        "perk_3": "Teamwork: Toughen Up",
        "difficulty": "Hard",
        "description": "A tactical former sheriff who crafts fragile temporary replacement pallets out of destroyed loops and draws killer aggro away from injured team members."
    },
    {
        "id": 48,
        "name": "Michonne",
        "character_code": "S48",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "None",
        "dlc": "Chapter 34.5: The Walking Dead",
        "year": 2025,
        "perk_1": "Conviction",
        "perk_2": "Last Stand",
        "perk_3": "Teamwork: Throw Down",
        "difficulty": "Hard",
        "description": "A fearless katana survivor who triggers high-stakes, single-use window stuns, picks herself up from the dying state, and grants defensive buffs."
    },
    {
        "id": 49,
        "name": "Vee Boonyasak",
        "character_code": "S49",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Thailand",
        "realm": "None",
        "dlc": "Chapter 36.5: Sinister Grace",
        "year": 2025,
        "perk_1": "Road Life",
        "perk_2": "ONE-TWO-THREE-FOUR!",
        "perk_3": "Ghost Notes",
        "difficulty": "Intermediate",
        "description": "An energetic punk rock drummer who utilizes rhythm performance actions to trigger team skill check bursts and slips out of loops with advanced stealth."
    },
    {
        "id": 50,
        "name": "Aurora Stardotter",
        "character_code": "S50",
        "role": "Survivor",
        "gender": "Female",
        "origin": "Terra Primus",
        "realm": "None",
        "dlc": "Chapter 38: Chorus of Sin",
        "year": 2026,
        "perk_1": "Starlight Beacon",
        "perk_2": "Cosmic Link",
        "perk_3": "Astral Projection",
        "difficulty": "Hard",
        "description": "An otherworldly astronaut who marks physical navigation points on the map and channels short distances to pass directly through solid tile walls."
    },
    {
        "id": 51,
        "name": "Cynthia Vance",
        "character_code": "S51",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United States",
        "realm": "Neon Metropolis",
        "dlc": "Chapter 39: Cyber Collapse",
        "year": 2026,
        "perk_1": "Overclocked System",
        "perk_2": "Data Siphon",
        "perk_3": "Grid runner",
        "difficulty": "Intermediate",
        "description": "A tech-renegade runner who hacks generator terminals to steal progress back from the killer and gains speed when stepping over electronic wire traps."
    },
    {
        "id": 52,
        "name": "Tariq Al-Amri",
        "character_code": "S52",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Jordan",
        "realm": "Shifting Sands",
        "dlc": "Chapter 40: Desert Mirage",
        "year": 2026,
        "perk_1": "Dust Cover",
        "perk_2": "Mirage Step",
        "perk_3": "Oasis Refresh",
        "difficulty": "Easy",
        "description": "A rugged desert archeologist who masks his visual pathing footprint by leaving behind decoys and rapidly cleanses hex totems using specialized tools."
    },
    {
        "id": 53,
        "name": "Evelyn Reed",
        "character_code": "S53",
        "role": "Survivor",
        "gender": "Female",
        "origin": "United Kingdom",
        "realm": "Asylum Depths",
        "dlc": "Chapter 41: Whispers of Mad",
        "year": 2026,
        "perk_1": "Quiet Mind",
        "perk_2": "Psychotherapy",
        "perk_3": "Deep Breath",
        "difficulty": "Easy",
        "description": "A mental health physician who limits the build-up of hallucination affliction effects and stabilizes terrified status conditions of near teammates."
    },
    {
        "id": 54,
        "name": "Kenji Sato",
        "character_code": "S54",
        "role": "Survivor",
        "gender": "Male",
        "origin": "Japan",
        "realm": "Asylum Depths",
        "dlc": "Chapter 41: Whispers of Mad",
        "year": 2026,
        "perk_1": "Adrenaline Rush",
        "perk_2": "Counter Strike",
        "perk_3": "Endurance Test",
        "difficulty": "Intermediate",
        "description": "An underground street brawler who temporarily withstands exposed damage effects and safely breaks killer window traps through raw physical stamina."
    },

    # =========================================================================
    # KILLERS
    # =========================================================================
    {
        "id": 55,
        "name": "The Trapper",
        "character_code": "K01",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "MacMillan Estate",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Unnerving Presence",
        "perk_2": "Brutal Strength",
        "perk_3": "Agitation",
        "difficulty": "Easy",
        "power": "Bear Trap",
        "description": "An area-control killer who sets hidden, physical steel bear traps across the map to catch, damage, and immobilize unwary survivors."
    },
    {
        "id": 56,
        "name": "The Wraith",
        "character_code": "K02",
        "role": "Killer",
        "gender": "Male",
        "origin": "Nigeria",
        "realm": "Autohaven Wreckers",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Predator",
        "perk_2": "Bloodhound",
        "perk_3": "Shadowborn",
        "difficulty": "Easy",
        "power": "Wailing Bell",
        "description": "A stealth killer who rings a mystical bell to turn completely invisible, allowing him to traverse the map swiftly and ambush survivors."
    },
    {
        "id": 57,
        "name": "The Hillbilly",
        "character_code": "K03",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Coldwind Farm",
        "dlc": "Base Game",
        "year": 2016,
        "perk_1": "Enduring",
        "perk_2": "Lightborn",
        "perk_3": "Tinkerer",
        "difficulty": "Easy",
        "power": "Chainsaw Sprint",
        "description": "A high-mobility, high-threat killer who charges forward at high speeds with his chainsaw, instantly downing any survivor caught in his path."
    },
    {
        "id": 58,
        "name": "The Nurse",
        "character_code": "K04",
        "role": "Killer",
        "gender": "Female",
        "origin": "United Kingdom",
        "realm": "Crotus Prenn Asylum",
        "dlc": "The Last Breath Chapter",
        "year": 2016,
        "perk_1": "A Nurse's Calling",
        "perk_2": "Stridor",
        "perk_3": "Thanatophobia",
        "difficulty": "Very Hard",
        "power": "Spencer's Last Breath",
        "description": "A hyper-lethal teleporting killer who blinks directly through solid obstacles and walls to immediately strike fleeing survivors."
    },
    {
        "id": 59,
        "name": "The Shape",
        "character_code": "K05",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Haddonfield",
        "dlc": "The Halloween Chapter",
        "year": 2016,
        "perk_1": "Save the Best for Last",
        "perk_2": "Play with Your Food",
        "perk_3": "Dying Light",
        "difficulty": "Intermediate",
        "power": "Evil Within",
        "description": "An imposing stalker killer (Michael Myers) who watches survivors from afar to charge his inner malice, granting permanent stat tiers and instant-down capabilities."
    },
    {
        "id": 60,
        "name": "The Hag",
        "character_code": "K06",
        "role": "Killer",
        "gender": "Female",
        "origin": "Undisclosed",
        "realm": "Backwater Swamp",
        "dlc": "Of Flesh and Mud Chapter",
        "year": 2016,
        "perk_1": "Hex: The Third Seal",
        "perk_2": "Hex: Ruin",
        "perk_3": "Hex: Devour Hope",
        "difficulty": "Intermediate",
        "power": "Phantasm Traps",
        "description": "A tactical teleportation killer who draws mud traps on the ground, warping straight to their position whenever a survivor triggers them by walking."
    },
    {
        "id": 61,
        "name": "The Doctor",
        "character_code": "K07",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Léry's Memorial Institute",
        "dlc": "Spark of Madness Chapter",
        "year": 2017,
        "perk_1": "Overwhelming Presence",
        "perk_2": "Monitor & Abuse",
        "perk_3": "Overcharge",
        "difficulty": "Easy",
        "power": "Carter's Spark",
        "description": "An oppressive disruption killer who releases localized madness shockwaves, driving survivors insane to reveal their locations and block interactions."
    },
    {
        "id": 62,
        "name": "The Huntress",
        "character_code": "K08",
        "role": "Killer",
        "gender": "Female",
        "origin": "Russia",
        "realm": "Red Forest",
        "dlc": "A Lullaby for the Dark Chapter",
        "year": 2017,
        "perk_1": "Beast of Prey",
        "perk_2": "Territorial Imperative",
        "perk_3": "Hex: Huntress Lullaby",
        "difficulty": "Intermediate",
        "power": "Hunting Hatchets",
        "description": "A deadly ranged killer who hurls sharp hatchets across loops and open maps, injuring or downing survivors from afar."
    },
    {
        "id": 63,
        "name": "The Cannibal",
        "character_code": "K09",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Leatherface Paragraph",
        "year": 2017,
        "perk_1": "Knock Out",
        "perk_2": "Barbecue & Chili",
        "perk_3": "Franklin's Demise",
        "difficulty": "Easy",
        "power": "Bubba's Chainsaw",
        "description": "A close-quarters threat killer (Leatherface) who swings his chainsaw in a wide, multi-hit sweeping tantrum, instantly downing any clusters of survivors."
    },
    {
        "id": 64,
        "name": "The Nightmare",
        "character_code": "K10",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Springwood",
        "dlc": "A Nightmare on Elm Street Chapter",
        "year": 2017,
        "perk_1": "Fire Up",
        "perk_2": "Remember Me",
        "perk_3": "Blood Warden",
        "difficulty": "Easy",
        "power": "Dream Demon",
        "description": "A surreal dreamscape killer (Freddy Krueger) who pulls survivors into a sleeping state, allowing him to teleport directly to generators and lay slowing blood traps."
    },
    {
        "id": 65,
        "name": "The Pig",
        "character_code": "K11",
        "role": "Killer",
        "gender": "Female",
        "origin": "United States",
        "realm": "Gideon Meat Plant",
        "dlc": "The SAW Chapter",
        "year": 2018,
        "perk_1": "Hangman's Trick",
        "perk_2": "Surveillance",
        "perk_3": "Make Your Choice",
        "difficulty": "Easy",
        "power": "Jigsaw's Baptism",
        "description": "A stealthy ambush killer (Amanda Young) who crouches to remove her terror radius, lunges out from corners, and places ticking Reverse Bear Traps on downed survivors."
    },
    {
        "id": 66,
        "name": "The Clown",
        "character_code": "K12",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Crotus Prenn Asylum",
        "dlc": "Curtain Call Chapter",
        "year": 2018,
        "perk_1": "The Third Seal",
        "perk_2": "Coulrophobia",
        "perk_3": "Pop Goes the Weasel",
        "difficulty": "Easy",
        "power": "The Afterpiece Tonic",
        "description": "A tactical anti-loop killer who throws bottles of toxic gas to blur visions and slow down survivors, while deploying yellow gas to speed up his own chases."
    },
    {
        "id": 67,
        "name": "The Spirit",
        "character_code": "K13",
        "role": "Killer",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Shattered Bloodline Chapter",
        "year": 2018,
        "perk_1": "Spirit Fury",
        "perk_2": "Hex: Haunted Ground",
        "perk_3": "Rancor",
        "difficulty": "Hard",
        "power": "Yamaoka's Haunting",
        "description": "A mind-game killer who detaches from her physical shell to travel invisibly through the spirit plane, tracking survivors purely via audio cues and scratch marks."
    },
    {
        "id": 68,
        "name": "The Legion",
        "character_code": "K14",
        "role": "Killer",
        "gender": "Group",
        "origin": "Canada",
        "realm": "Ormond",
        "dlc": "Darkness Among Us Chapter",
        "year": 2018,
        "perk_1": "Discordance",
        "perk_2": "Madness",
        "perk_3": "Iron Maiden",
        "difficulty": "Easy",
        "power": "Feral Frenzy",
        "description": "A fast-paced hit-and-run killer squad that sprint vaults over windows and pallets to rapidly stab multiple survivors, applying the bleeding Deep Wound status."
    },
    {
        "id": 69,
        "name": "The Plague",
        "character_code": "K15",
        "role": "Killer",
        "gender": "Female",
        "origin": "Babylon",
        "realm": "Plague Realm",
        "dlc": "Demise of the Faithful Chapter",
        "year": 2019,
        "perk_1": "Corrupt Intervention",
        "perk_2": "Infectious Fright",
        "perk_3": "Dark Devotion",
        "difficulty": "Intermediate",
        "power": "Vile Purge",
        "description": "A systematic affliction killer who vomits contagious bile onto objects and survivors, forcing them into a permanently broken, vomiting, and trackable state."
    },
    {
        "id": 70,
        "name": "The Ghost Face",
        "character_code": "K16",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Ghost Face Paragraph",
        "year": 2019,
        "perk_1": "I'm All Ears",
        "perk_2": "Thrilling Tremors",
        "perk_3": "Furtive Chase",
        "difficulty": "Easy",
        "power": "Night Shroud",
        "description": "A methodical stealth killer who hides his red stain and terror radius completely, leaning around corners to stalk and expose individual survivors."
    },
    {
        "id": 71,
        "name": "The Demogorgon",
        "character_code": "K17",
        "role": "Killer",
        "gender": "Male",
        "origin": "The Upside Down",
        "realm": "Hawkins National Laboratory",
        "dlc": "Stranger Things Chapter",
        "year": 2019,
        "perk_1": "Surge",
        "perk_2": "Cruel Limits",
        "perk_3": "Mindbreaker",
        "difficulty": "Intermediate",
        "power": "Of the Abyss",
        "description": "A monstrous apex predator that lunges long distances across loops to shred pallets and tears open organic ground portals to travel under the map."
    },
    {
        "id": 72,
        "name": "The Oni",
        "character_code": "K18",
        "role": "Killer",
        "gender": "Male",
        "origin": "Japan",
        "realm": "Yamaoka Estate",
        "dlc": "Cursed Legacy Chapter",
        "year": 2019,
        "perk_1": "Zanshin Tactics",
        "perk_2": "Blood Echo",
        "perk_3": "Nemesis",
        "difficulty": "Hard",
        "power": "Yamaoka's Wrath",
        "description": "A high-momentum snowball killer who absorbs glowing blood orbs dropped by injured survivors to trigger a raging state, gaining map-wide dash speeds and lethal clubs."
    },
    {
        "id": 73,
        "name": "The Deathslinger",
        "character_code": "K19",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Grave of Glenvale",
        "dlc": "Chains of Hate Chapter",
        "year": 2020,
        "perk_1": "Gearhead",
        "perk_2": "Dead Man's Switch",
        "perk_3": "Hex: Retribution",
        "difficulty": "Intermediate",
        "power": "The Redeemer",
        "description": "An inventive ranged killer who fires a mechanical harpoon gun to impale survivors, reeling them in closer across obstacles for a basic attack blow."
    },
    {
        "id": 74,
        "name": "The Executioner",
        "character_code": "K20",
        "role": "Killer",
        "gender": "Male",
        "origin": "Silent Hill",
        "realm": "Midwich Elementary School",
        "dlc": "Silent Hill Chapter",
        "year": 2020,
        "perk_1": "Forced Penance",
        "perk_2": "Trail of Torment",
        "perk_3": "Deathbound",
        "difficulty": "Hard",
        "power": "Rites of Judgement",
        "description": "A heavy control killer (Pyramid Head) who carves trenches into the floor to afflict survivors, bypassing standard hook mechanics entirely via Cages of Atonement."
    },
    {
        "id": 75,
        "name": "The Blight",
        "character_code": "K21",
        "role": "Killer",
        "gender": "Male",
        "origin": "Scotland",
        "realm": "Undisclosed",
        "dlc": "Descend Beyond Chapter",
        "year": 2020,
        "perk_1": "Dragon's Grip",
        "perk_2": "Hex: Blood Favor",
        "perk_3": "Hex: Undying",
        "difficulty": "Very Hard",
        "power": "Blighted Rush",
        "description": "A high-speed kinetic killer who drinks serum to bounce aggressively off environmental walls, launching lightning-fast lethal rush strikes down loops."
    },
    {
        "id": 76,
        "name": "The Twins",
        "character_code": "K22",
        "role": "Killer",
        "gender": "Group",
        "origin": "France",
        "realm": "Undisclosed",
        "dlc": "A Binding of Kin Chapter",
        "year": 2020,
        "perk_1": "Hoarder",
        "perk_2": "Oppression",
        "perk_3": "Coupe de Grâce",
        "difficulty": "Very Hard",
        "power": "Blood Bond",
        "description": "A dual-character tag killer who splits her conjoined twin Victor from Charlotte's chest, controlling him to run at high speed and pounce on survivor backs."
    },
    {
        "id": 77,
        "name": "The Trickster",
        "character_code": "K23",
        "role": "Killer",
        "gender": "Male",
        "origin": "South Korea",
        "realm": "All-Kill Realm",
        "dlc": "All-Kill Chapter",
        "year": 2021,
        "perk_1": "Starstruck",
        "perk_2": "Hex: Crowd Control",
        "perk_3": "No Way Out",
        "difficulty": "Easy",
        "power": "Showstopper",
        "description": "A flamboyant ranged killer who unleashes rapid-fire volleys of throwing knives to fill up a survivor's laceration meter from medium range."
    },
    {
        "id": 78,
        "name": "The Nemesis",
        "character_code": "K24",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil Chapter",
        "year": 2021,
        "perk_1": "Lethal Pursuer",
        "perk_2": "Hysteria",
        "perk_3": "Eruption",
        "difficulty": "Easy",
        "power": "T-Virus",
        "description": "An evolving juggernaut bio-weapon killer who whips survivors with an infection tentacle to increase his power reach, supported by roaming AI zombies."
    },
    {
        "id": 79,
        "name": "The Cenobite",
        "character_code": "K25",
        "role": "Killer",
        "gender": "Male",
        "origin": "Labyrinth",
        "realm": "Base Game",
        "dlc": "Hellraiser Paragraph",
        "year": 2021,
        "perk_1": "Deadlock",
        "perk_2": "Hex: Plaything",
        "perk_3": "Scourge Hook: Gift of Pain",
        "difficulty": "Hard",
        "power": "Summons of Pain",
        "description": "A global harassment killer (Pinhead) who shoots guided gateway hooks to tie down survivors, forcing them to find a puzzle box to halt constant passive chain attacks."
    },
   {
        "id": 80,
        "name": "The Artist",
        "character_code": "K26",
        "role": "Killer",
        "gender": "Female",
        "origin": "Chile",
        "realm": "Eyrie of Crows",
        "dlc": "Portrait of a Murder Chapter",
        "year": 2021,
        "perk_1": "Grim Embrace",
        "perk_2": "Scourge Hook: Pain Resonance",
        "perk_3": "Hex: Pentimento",
        "difficulty": "Intermediate",
        "power": "Birds of Torment",
        "description": "A tactical long-distance cross-map killer who sets ink crows on walls, firing them directly through solid objects to swarm or injure survivors across the realm."
    },
    {
        "id": 81,
        "name": "The Onryō",
        "character_code": "K27",
        "role": "Killer",
        "gender": "Female",
        "origin": "Japan",
        "realm": "Base Game",
        "dlc": "Sadako Rising Chapter",
        "year": 2022,
        "perk_1": "Scourge Hook: Floods of Rage",
        "perk_2": "Call of Brine",
        "perk_3": "Merciless Storm",
        "difficulty": "Intermediate",
        "power": "Deluge of Fear",
        "description": "A creeping psychological curse killer (Sadako) who manifests out of active TV monitors to build up Condemned status layers on survivors, allowing instant executions."
    },
    {
        "id": 82,
        "name": "The Dredge",
        "character_code": "K28",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "Undisclosed",
        "realm": "Garden of Joy",
        "dlc": "Roots of Dread Chapter",
        "year": 2022,
        "perk_1": "Dissolution",
        "perk_2": "Darkness Revealed",
        "perk_3": "Septic Touch",
        "difficulty": "Intermediate",
        "power": "Reign of Darkness",
        "description": "An amorphous manifestation of negative energy that teleports inside map lockers, materializes remnants during loops, and triggers a pitch-black Nightfall shroud."
    },
    {
        "id": 83,
        "name": "The Mastermind",
        "character_code": "K29",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Raccoon City Police Department",
        "dlc": "Resident Evil: PROJECT W Chapter",
        "year": 2022,
        "perk_1": "Superior Anatomy",
        "perk_2": "Awakened Awareness",
        "perk_3": "Terminus",
        "difficulty": "Intermediate",
        "power": "Virulent Bound",
        "description": "A high-speed bio-engineered predator (Albert Wesker) who dashes twice to grab and throw survivors, infecting them with a slowing Uroboros pathogen."
    },
    {
        "id": 84,
        "name": "The Knight",
        "character_code": "K30",
        "role": "Killer",
        "gender": "Male",
        "origin": "Italy",
        "realm": "The Shattered Square",
        "dlc": "Forged in Fog Chapter",
        "year": 2022,
        "perk_1": "Nowhere to Hide",
        "perk_2": "Hex: Face the Darkness",
        "perk_3": "Hubris",
        "difficulty": "Intermediate",
        "power": "Guardia Compagnia",
        "description": "A tactical squad commander killer who draws physical search paths to summon AI spectral guards, tasking them to destroy objects or hunt survivors down."
    },
    {
        "id": 85,
        "name": "The Skull Merchant",
        "character_code": "K31",
        "role": "Killer",
        "gender": "Female",
        "origin": "Brazil",
        "realm": "Shelter Woods",
        "dlc": "Tools of Torment Chapter",
        "year": 2023,
        "perk_1": "Thwack!",
        "perk_2": "Leverage",
        "perk_3": "Game Afoot",
        "difficulty": "Easy",
        "power": "Eyes in the Sky",
        "description": "A high-tech hunting tracker who deploys spinning surveillance drones to map out territories, exposing survivors and tracking their exact positions."
    },
    {
        "id": 86,
        "name": "The Singularity",
        "character_code": "K32",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "Toba Landing",
        "realm": "Toba Landing",
        "dlc": "End Transmission Chapter",
        "year": 2023,
        "perk_1": "Genetic Limits",
        "perk_2": "Forced Hesitation",
        "perk_3": "Machine Learning",
        "difficulty": "Very Hard",
        "power": "Quantum Instantiation",
        "description": "A corrupted AI lifeform that shoots biopod cameras onto structural surfaces, shooting slipstream nodes onto survivors to teleport straight behind them."
    },
    {
        "id": 87,
        "name": "The Xenomorph",
        "character_code": "K33",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "Nostromo Wreckage",
        "realm": "Nostromo Wreckage",
        "dlc": "Alien Chapter",
        "year": 2023,
        "perk_1": "Rapid Brutality",
        "perk_2": "Alien Instinct",
        "perk_3": "Ultimate Weapon",
        "difficulty": "Easy",
        "power": "Hidden Pursuit",
        "description": "An iconic alien predator that crawls on all fours through sub-surface floor tunnels, emerging at control stations to strike loops using a razor-sharp tail lash."
    },
    {
        "id": 88,
        "name": "The Good Guy",
        "character_code": "K34",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "Base Game",
        "dlc": "Chucky Chapter",
        "year": 2023,
        "perk_1": "Hex: Two Can Play",
        "perk_2": "Friends 'Til the End",
        "perk_3": "Batteries Included",
        "difficulty": "Hard",
        "power": "Playtime's Over",
        "description": "A diminutive, third-person perspective killer doll (Chucky) who completely hides his physical form in white footprints, launching scamper slice rushes under loops."
    },
    {
        "id": 89,
        "name": "The Unknown",
        "character_code": "K35",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "United States",
        "realm": "Forgotten Ruins",
        "dlc": "All Things Wicked Chapter",
        "year": 2024,
        "perk_1": "Unbound",
        "perk_2": "Unforeseen",
        "perk_3": "Undone",
        "difficulty": "Hard",
        "power": "UVX",
        "description": "A bizarre cryptid horror that bounces structural venom toxins off loop walls to weaken survivors, dropping stationary decoys to instantly teleport across tiles."
    },
    {
        "id": 90,
        "name": "The Lich",
        "character_code": "K36",
        "role": "Killer",
        "gender": "Male",
        "origin": "Oerth",
        "realm": "Forgotten Ruins",
        "dlc": "Dungeons & Dragons Chapter",
        "year": 2024,
        "perk_1": "Languid Bleed",
        "perk_2": "Weave Attunement",
        "perk_3": "Dark Arrogance",
        "difficulty": "Hard",
        "power": "Vile Book of Spells",
        "description": "An ancient sorcerer (Vecna) who toggles through four magical spell types to lift dropped pallets, fly over gaps, track items, or launch magical skeletons."
    },
    {
        "id": 91,
        "name": "The Dark Lord",
        "character_code": "K37",
        "role": "Killer",
        "gender": "Male",
        "origin": "Wallachia",
        "realm": "Castle Dracula",
        "dlc": "Castlevania Chapter",
        "year": 2024,
        "perk_1": "Dominance",
        "perk_2": "Human Frailty",
        "perk_3": "Exquisite Blood",
        "difficulty": "Hard",
        "power": "Vampiric Powers",
        "description": "A shape-shifting vampire king (Dracula) who transitions between Vampire form to cast hellfire columns, Wolf form to chase scent tracks, and Bat form to teleport over vaults."
    },
    {
        "id": 92,
        "name": "The Hound",
        "character_code": "K38",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "The Void",
        "dlc": "Doomed Echoes Chapter",
        "year": 2024,
        "perk_1": "Scent of Blood",
        "perk_2": "Cornered Prey",
        "perk_3": "Terrible Maw",
        "difficulty": "Intermediate",
        "power": "Savage Hunt",
        "description": "A feral tracker killer that moves on all fours to follow scent trails left by running survivors, executing extended bite lunges that apply heavy hemorrhage."
    },
    {
        "id": 93,
        "name": "The Ghoul",
        "character_code": "K39",
        "role": "Killer",
        "gender": "Male",
        "origin": "Japan",
        "realm": "None",
        "dlc": "Chapter 35: Tokyo Ghoul",
        "year": 2025,
        "perk_1": "Hex: Nothing But Misery",
        "perk_2": "Forever Entwined",
        "perk_3": "None Are Free",
        "difficulty": "Intermediate",
        "power": "One-Eyed Terror",
        "description": "An aggressive, half-ghoul killer who thrives on slowing survivors in chases, speeding up hook pickups, and locking down windows and standing pallets during the endgame."
    },
    {
        "id": 95,
        "name": "The Krasue",
        "character_code": "K41",
        "role": "Killer",
        "gender": "Female",
        "origin": "Thailand",
        "realm": "None",
        "dlc": "Chapter 37: Sinister Grace",
        "year": 2025,
        "perk_1": "Ravenous",
        "perk_2": "Wandering Eye",
        "perk_3": "Hex: Overture of Doom",
        "difficulty": "Hard",
        "power": "Visceral Flight",
        "description": "A split-form killer inspired by Thai folklore who detaches her floating head to lunge out with a long-range Intestinal Whip, while her perks maximize map-wide tracking, false terror radii, and sudden endgame pressure."
    },
    {
        "id": 96,
        "name": "The Slasher",
        "character_code": "K35_JV",
        "role": "Killer",
        "gender": "Male",
        "origin": "United States",
        "realm": "None",
        "dlc": "Chapter 40: Jason",
        "year": 2026,
        "perk_1": "Hex: Scared to Death",
        "perk_2": "Silent Shadow",
        "perk_3": "Rampage",
        "difficulty": "Easy",
        "power": "Omnipresent Evil",
        "description": "A relentless, masked powerhouse (Jason Voorhees) who blends high-speed invisible map teleportation with a brutal projectile-flinging mechanics to isolate and pin down survivors."
    },
    {
        "id": 97,
        "name": "The Judgment",
        "character_code": "K42",
        "role": "Killer",
        "gender": "Genderless",
        "origin": "Terra Primus",
        "realm": "None",
        "dlc": "Chapter 38: Chorus of Sin",
        "year": 2026,
        "perk_1": "Celestial Witness",
        "perk_2": "Hex: Under Your Thumb",
        "perk_3": "Lay Waste",
        "difficulty": "Very Hard",
        "power": "Divine Condemned",
        "description": "A punishing celestial entity that casts down columns of divine light to brand survivors with Heresy, allowing it to banish downed heretics straight into the grueling trial of Exile."
    }

   

# =========================================================================
# API ENDPOINTS
# =========================================================================

@app.get("/")
def home():
    return {
        "message": "Welcome to the Dead by Daylight Character Directory API!",
        "total_characters": len(characters),
        "survivors_count": len([c for c in characters if c["role"] == "Survivor"]),
        "killers_count": len([c for c in characters if c["role"] == "Killer"]),
        "endpoints": [
            "/api/characters",
            "/api/characters/{character_id}",
            "/api/characters/search"
        ]
    }

# GET ALL CHARACTERS (WITH ROLE FILTER, PAGINATION, AND SORTING)
@app.get("/characters")
def get_characters(
    role: str = Query(None, description="Filter by 'Survivor' or 'Killer'"),
    sort_by: str = Query("name", description="Sort field: 'name', 'year', 'difficulty', 'character_code'"),
    order: str = Query("asc", description="'asc' or 'desc'"),
    limit: int = Query(10, ge=1, le=100, description="Items per page (default: 10)"),
    offset: int = Query(0, ge=0, description="Page starting offset")
):
    results = characters

    # Filter by role
    if role:
        results = [c for c in results if c["role"].lower() == role.lower()]

    # Sort results
    reverse = (order.lower() == "desc")
    if sort_by in ["name", "year", "difficulty", "character_code"]:
        results = sorted(results, key=lambda x: str(x.get(sort_by, "")).lower(), reverse=reverse)

    # Paginate results
    total_count = len(results)
    paginated_results = results[offset : offset + limit]

    return {
        "total": total_count,
        "limit": limit,
        "offset": offset,
        "characters": paginated_results
    }

# SEARCH CHARACTERS BY ANY KEYWORD
@app.get("/characters/search")
def search_characters(
    q: str = Query(..., min_length=1),
    limit: int = Query(10, ge=1, le=100),
    offset: int = Query(0, ge=0)
):
    q = q.lower()
    matched = []
    for c in characters:
        searchable_text = (
            f"{c['character_code']} "
            f"{c['name']} "
            f"{c['role']} "
            f"{c['gender']} "
            f"{c['origin']} "
            f"{c['realm']} "
            f"{c['dlc']} "
            f"{c['year']} "
            f"{c['perk_1']} "
            f"{c['perk_2']} "
            f"{c['perk_3']} "
            f"{c['difficulty']} "
            f"{c.get('power', '')}"
        ).lower()

        if q in searchable_text:
            matched.append(c)
    paginated_results = matched[offset : offset + limit]
    return {
        "query": q,
        "total": len(matched),
        "limit": limit,
        "offset": offset,
        "results": paginated_results
    }
# GET SINGLE CHARACTER BY ID
@app.get("/characters/{character_id}")
def get_character(character_id: int):
    for c in characters:
        if c["id"] == character_id:
            return c

    raise HTTPException(
        status_code=404,
        detail="Character not found."
    )
